<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="LASER Institute">
<meta name="dcterms.date" content="2024-07-15">

<title>SNA Case Study: Birds of a Feather Lead Together</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="sna-4-case-study-key-R_files/libs/clipboard/clipboard.min.js"></script>
<script src="sna-4-case-study-key-R_files/libs/quarto-html/quarto.js"></script>
<script src="sna-4-case-study-key-R_files/libs/quarto-html/popper.min.js"></script>
<script src="sna-4-case-study-key-R_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="sna-4-case-study-key-R_files/libs/quarto-html/anchor.min.js"></script>
<link href="sna-4-case-study-key-R_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="sna-4-case-study-key-R_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="sna-4-case-study-key-R_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="sna-4-case-study-key-R_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="sna-4-case-study-key-R_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="sna-4-case-study-key-R_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="sna-4-case-study-key-R_files/libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#prepare" id="toc-prepare" class="nav-link active" data-scroll-target="#prepare">1. PREPARE</a>
  <ul>
  <li><a href="#a.-review-the-research" id="toc-a.-review-the-research" class="nav-link" data-scroll-target="#a.-review-the-research">1a. Review the Research</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a>
  <ul class="collapse">
  <li><a href="#abstract" id="toc-abstract" class="nav-link" data-scroll-target="#abstract">Abstract</a></li>
  </ul></li>
  <li><a href="#your-turn" id="toc-your-turn" class="nav-link" data-scroll-target="#your-turn">👉 Your Turn&nbsp;⤵</a>
  <ul class="collapse">
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">Research Questions</a></li>
  <li><a href="#data-collection" id="toc-data-collection" class="nav-link" data-scroll-target="#data-collection">Data Collection</a></li>
  <li><a href="#analyses" id="toc-analyses" class="nav-link" data-scroll-target="#analyses">Analyses</a></li>
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings">Key Findings</a></li>
  <li><a href="#your-turn-1" id="toc-your-turn-1" class="nav-link" data-scroll-target="#your-turn-1">👉 Your Turn ⤵</a></li>
  </ul></li>
  <li><a href="#b.-load-libraries" id="toc-b.-load-libraries" class="nav-link" data-scroll-target="#b.-load-libraries">1b. Load Libraries</a>
  <ul class="collapse">
  <li><a href="#statnet" id="toc-statnet" class="nav-link" data-scroll-target="#statnet">statnet 📦</a></li>
  <li><a href="#your-turn-2" id="toc-your-turn-2" class="nav-link" data-scroll-target="#your-turn-2">👉 Your Turn ⤵</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#wrangle" id="toc-wrangle" class="nav-link" data-scroll-target="#wrangle">2. WRANGLE</a>
  <ul>
  <li><a href="#a.-import-data" id="toc-a.-import-data" class="nav-link" data-scroll-target="#a.-import-data">2a. Import Data</a>
  <ul class="collapse">
  <li><a href="#your-turn-3" id="toc-your-turn-3" class="nav-link" data-scroll-target="#your-turn-3">👉 Your Turn ⤵</a></li>
  </ul></li>
  <li><a href="#b.-dichotomize-matrix" id="toc-b.-dichotomize-matrix" class="nav-link" data-scroll-target="#b.-dichotomize-matrix">2b. Dichotomize Matrix</a>
  <ul class="collapse">
  <li><a href="#add-row-and-column-names" id="toc-add-row-and-column-names" class="nav-link" data-scroll-target="#add-row-and-column-names">Add Row and Column Names</a></li>
  </ul></li>
  <li><a href="#c.-create-network-with-attributes" id="toc-c.-create-network-with-attributes" class="nav-link" data-scroll-target="#c.-create-network-with-attributes">2c. Create Network with Attributes</a>
  <ul class="collapse">
  <li><a href="#get-edges" id="toc-get-edges" class="nav-link" data-scroll-target="#get-edges">Get Edges</a></li>
  <li><a href="#your-turn-4" id="toc-your-turn-4" class="nav-link" data-scroll-target="#your-turn-4">👉 Your Turn ⤵</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#explore" id="toc-explore" class="nav-link" data-scroll-target="#explore">3. EXPLORE</a>
  <ul>
  <li><a href="#a.-examine-descriptives" id="toc-a.-examine-descriptives" class="nav-link" data-scroll-target="#a.-examine-descriptives">3a. Examine Descriptives</a>
  <ul class="collapse">
  <li><a href="#calculate-node-degree" id="toc-calculate-node-degree" class="nav-link" data-scroll-target="#calculate-node-degree">Calculate Node Degree</a></li>
  <li><a href="#your-turn-5" id="toc-your-turn-5" class="nav-link" data-scroll-target="#your-turn-5">👉 Your Turn ⤵</a></li>
  <li><a href="#summarize-node-measures" id="toc-summarize-node-measures" class="nav-link" data-scroll-target="#summarize-node-measures">Summarize Node Measures</a></li>
  <li><a href="#schooldistrict-level-stats" id="toc-schooldistrict-level-stats" class="nav-link" data-scroll-target="#schooldistrict-level-stats">School/District-Level Stats</a></li>
  <li><a href="#your-turn-6" id="toc-your-turn-6" class="nav-link" data-scroll-target="#your-turn-6">👉 Your Turn ⤵</a></li>
  </ul></li>
  <li><a href="#b.-visualize-network-properties" id="toc-b.-visualize-network-properties" class="nav-link" data-scroll-target="#b.-visualize-network-properties">3b. Visualize Network Properties</a>
  <ul class="collapse">
  <li><a href="#your-turn-7" id="toc-your-turn-7" class="nav-link" data-scroll-target="#your-turn-7">👉 Your Turn ⤵</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">4. MODEL</a>
  <ul>
  <li><a href="#a.-loading-network-data" id="toc-a.-loading-network-data" class="nav-link" data-scroll-target="#a.-loading-network-data">4a. Loading Network Data</a></li>
  <li><a href="#b.-estimate-the-ergm" id="toc-b.-estimate-the-ergm" class="nav-link" data-scroll-target="#b.-estimate-the-ergm">4b. Estimate the ERGM</a>
  <ul class="collapse">
  <li><a href="#network-structure-parameters" id="toc-network-structure-parameters" class="nav-link" data-scroll-target="#network-structure-parameters">Network Structure Parameters</a></li>
  <li><a href="#actor-attribute-parameters" id="toc-actor-attribute-parameters" class="nav-link" data-scroll-target="#actor-attribute-parameters">Actor Attribute Parameters</a></li>
  <li><a href="#your-turn-8" id="toc-your-turn-8" class="nav-link" data-scroll-target="#your-turn-8">👉 Your Turn ⤵</a></li>
  </ul></li>
  <li><a href="#c.-check-model-fit" id="toc-c.-check-model-fit" class="nav-link" data-scroll-target="#c.-check-model-fit">4c. Check Model Fit</a>
  <ul class="collapse">
  <li><a href="#the-gof-function" id="toc-the-gof-function" class="nav-link" data-scroll-target="#the-gof-function">The GOF Function</a></li>
  <li><a href="#check-mcnc-diagnostics" id="toc-check-mcnc-diagnostics" class="nav-link" data-scroll-target="#check-mcnc-diagnostics">Check MCNC Diagnostics</a></li>
  <li><a href="#your-turn-9" id="toc-your-turn-9" class="nav-link" data-scroll-target="#your-turn-9">👉 Your Turn ⤵</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#communicate" id="toc-communicate" class="nav-link" data-scroll-target="#communicate">5. COMMUNICATE</a>
  <ul>
  <li><a href="#render-file" id="toc-render-file" class="nav-link" data-scroll-target="#render-file">Render File</a>
  <ul class="collapse">
  <li><a href="#your-turn-10" id="toc-your-turn-10" class="nav-link" data-scroll-target="#your-turn-10">👉 Your Turn ⤵</a></li>
  </ul></li>
  <li><a href="#publish-file" id="toc-publish-file" class="nav-link" data-scroll-target="#publish-file">Publish File</a>
  <ul class="collapse">
  <li><a href="#your-turn-11" id="toc-your-turn-11" class="nav-link" data-scroll-target="#your-turn-11">👉 Your Turn ⤵</a></li>
  <li><a href="#publishing-with-quarto-pub" id="toc-publishing-with-quarto-pub" class="nav-link" data-scroll-target="#publishing-with-quarto-pub">Publishing with Quarto Pub</a></li>
  <li><a href="#publishing-with-r-pubs" id="toc-publishing-with-r-pubs" class="nav-link" data-scroll-target="#publishing-with-r-pubs">Publishing with R Pubs</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">SNA Case Study: Birds of a Feather Lead Together</h1>
<p class="subtitle lead">SNA Module 4: Case Study Key</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>LASER Institute </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 15, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="prepare" class="level2">
<h2 class="anchored" data-anchor-id="prepare">1. PREPARE</h2>
<p>In Social Network Analysis and Education: Theory, Methods &amp; Applications <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span> makes the following distinctions between mathematical and statistical approaches to social network analysis:</p>
<ol type="1">
<li><p><strong>Mathematical approaches</strong> focus on what a network of actors “looks like” by describing the network using sociograms and/or network measures such as reciprocity, centrality, and density. However, these approaches “tend to regard the measured relationships and their strengths as accurately reflecting the real, final, or equilibrium status of the network.”</p></li>
<li><p><strong>Statistical approaches</strong>, or statistical inference, on the other hand, focuses on “assessing the reproducibility or likelihood of an observed pattern” with the goal of explaining and ultimately predicting network structures and outcomes.</p></li>
</ol>
<p><em>SNA Case Study: Birds of a Feather Lead Together</em> is guided once again by the work of Alan Daly and colleagues and moves beyond “mathematical approaches” highlighted in previous labs and introduces the use of ERGMs as a “statistical approach” to network analysis. Specifically, we will try to replicate the P* models used in Chapter 9 of <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span> in order to test hypotheses about individual and network characteristics that may explain who school leaders select for collaboration and confidential exchanges.</p>
<p>More specifically, this case study will cover the following topics pertaining to each data-intensive workflow process:</p>
<ol type="1">
<li><p><strong>Prepare</strong>: Prior to analysis, we’ll take a look at look at the study by Daly and Finnigan from whence our data was derived, formulate some research questions, and get introduced the {statnet} R package for ERGMs.</p></li>
<li><p><strong>Wrangle</strong>: In section 2 we will learn how to work with matrices, how to dichotomize matrices, and how to convert matrices into more workable formats like our familiar edge-list.</p></li>
<li><p><strong>Explore</strong>: In section 3, we once again use the {tidygraph} package and the companion {ggraph} package to calculate basic summary stats for our network and will try to replicate and ideally improve upon the sociogram from our readings.</p></li>
<li><p><strong>Model</strong>: We wrap up our analysis in Section 4 by introducing exponential random graph modules used in Chapter 9 of <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span>, learn to check how well our model “fits our data” and examine diagnostics that might indicate issues with our model.</p></li>
<li><p><strong>Communicate</strong>: Finally, we’ll select, polish, and narrate a key finding from our analysis that helps to answer or research question(s).</p></li>
</ol>
<section id="a.-review-the-research" class="level3">
<h3 class="anchored" data-anchor-id="a.-review-the-research">1a. Review the Research</h3>
</section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
<p><img src="img/ebb-flow.png" class="img-fluid" style="width:40.0%"></p>
<p>Daly, A. J., &amp; Finnigan, K. S. (2011). The ebb and flow of social network ties between district leaders under high-stakes accountability. <em>American Educational Research Journal</em>, <em>48</em>(1), 39-79.</p>
<section id="abstract" class="level4">
<h4 class="anchored" data-anchor-id="abstract">Abstract</h4>
<p>Recent scholarship suggests the importance of school district offices in supporting reform. These studies provide strategies for building relations between central offices and sites in order to improve change efforts. However, what is frequently overlooked is that organizational reform efforts are socially constructed. Therefore, examining the underlying reform-related social networks may provide insight into how relational structures support or constrain efforts at reform. This longitudinal case study draws upon social network analysis and interviews to examine the reform-related knowledge, advice, and innovation network structures of central office and site leaders in a district facing sanction for underperformance and engaging a districtwide reform. Findings indicate that over time, the networks increased the number of superficial interactions, and more frequent exchanges remained unchanged, resulting in a centralized network structure.</p>
</section>
</section>
<section id="your-turn" class="level3">
<h3 class="anchored" data-anchor-id="your-turn">👉 Your Turn&nbsp;⤵</h3>
<p>Take a look at the article <em>The Ebb and Flow of Social Network Ties Between District Leaders Under High-Stakes Accountability</em> located in the lit folder of your files pane and answer the following questions:</p>
<ol type="1">
<li><p>What research questions were the authors of this study trying to address and why did they consider these questions important?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>How were participants selected for this study and what was the rationale?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>How did the authors collect social network data for this study and what specific information about actors and ties were collected?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>What models were employed in this study and how was statistical inference used to address the research questions?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
<section id="research-questions" class="level4">
<h4 class="anchored" data-anchor-id="research-questions">Research Questions</h4>
<p>For this case study, we will be using school leadership data were collected at two school districts over 3 consecutive years that was used to answer the following research questions below:</p>
<ol type="1">
<li>Is there a relationship between the frequency of collaboration between school leaders and how often they turn to each other to discuss issues of a confidential nature?</li>
<li>Do school leaders prefer to collaborate with those with whom they have collaborated in the past, or is there some other reason?</li>
<li><strong>Does gender or some other individual attribute predicts confidential exchanges between school leaders, or does some previous relation have a stronger effect?</strong></li>
<li>Does collaboration between leaders explain one’s level of trust in one’s administrative colleagues?</li>
<li>Can we distinguish among different groups of school leaders based on how frequently they collaborate, and if so, are these groupings related to the level at which they work (school versus district)?</li>
</ol>
<p>Of specific interest for our case study is research question 3 emphasized in bold text above, which asks whether individual attributes predicts tie formation. For example, are males more likely to engage in exchange confidential exchanges with other.</p>
<blockquote class="blockquote">
<p>The tendency for individuals to be attracted to and interact with others who share similar characteristics is formally referred to as <strong>homophily or assortativity</strong>, but more commonly known by the “birds of a feather flock together” proverb.</p>
</blockquote>
<p>Homophily has been well documented in education research across a variety of relation types including student friendships, teacher-pupil interactions, and membership in student cohorts <span class="citation" data-cites="mcpherson1987homophily">(<a href="#ref-mcpherson1987homophily" role="doc-biblioref">McPherson and Smith-Lovin 1987</a>)</span>. Studies of homophily among student friendships, for example, date back to the 1920’s and provide strong evidence that students form ties based on sociodemographic similarities.</p>
</section>
<section id="data-collection" class="level4">
<h4 class="anchored" data-anchor-id="data-collection">Data Collection</h4>
<p>For each consecutive year, school district leaders were invited to complete a survey that collected individual:</p>
<ul>
<li><p><strong>Demographic information</strong> (e.g., gender, ethnicity, marital status, age, years of experiences);</p></li>
<li><p><strong>Network relationships types</strong> (e.g., collaboration, confidential exchanges, energy, expertise, leaders approached for support, work-related issues, input, recognition, best practices, and innovation);</p></li>
<li><p><strong>Frequency of interactions</strong> they have with those nominated individuals on a four-point frequency scale ranging from 1 (the least frequent) to 4 (1–2 times a week);</p></li>
<li><p><strong>Leadership efficacy</strong> items were designed based on the Principal Efficacy Scale used in Daly et al.&nbsp;(2011) and Tschannen-Moran and Gareis’s (2004) studies. The efficacy scale includes 18 items rated on a 9-point Likert scale ranging from 1 (None at all) to 9 (A great deal);</p></li>
<li><p><strong>Trust</strong> scale contains eight items rated on a 7-point Likert scale ranging from 1 (Strongly disagree) to 7 (Strongly agree) modified from Tschannen-Moran and Hoy (2003).</p></li>
</ul>
</section>
<section id="analyses" class="level4">
<h4 class="anchored" data-anchor-id="analyses">Analyses</h4>
<p>Two modeling techniques unique to network analysis and demonstrated in Chapter 9 of <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span> are the quadratic assignment procedure (QAP) and Exponential Random Graph Models (ERGM):</p>
<ul>
<li><p><strong>QAP/MR</strong>: The quadratic assignment procedure (QAP) developed by Hubert (1987) and Krackhardt (1987b) tests the null hypothesis of no correlation between the two networks and adjusts for this dependence between networks by repeatedly permuting the order of rows and columns of one of the networks while keeping the other network intact. The QAP is based on regression models and permutation tests for valued (i.e., continuous) relational variables.</p></li>
<li><p><strong>P1 and P* (P-Star)</strong>: Both of these models are some of the first to make use of the ERGM, which provides a basis for comparing whether a network’s observed structural properties occur more frequently than you could expect from chance alone. ERGMs can be used to model ties in complete networks but do so in a manner that explains the presence (or absence) of ties as a function of individual-and/or network-level characteristics. While QAP and MR-QAP procedures control for network structure through permutations, these ERGMs attempt to explain it.</p></li>
</ul>
</section>
<section id="key-findings" class="level4">
<h4 class="anchored" data-anchor-id="key-findings">Key Findings</h4>
<p>In response to research questions 1 &amp; 2 from above, Carolyn reported that “while collaboration in year 1 does not significantly predict collaboration in year 3, confidential exchanges in year 1 does” and suggested that “collaboration among school leaders provides an important foundation for more sensitive, perhaps even deeper, relations (e.g., confidential exchanges) at a later point in time.”</p>
</section>
<section id="your-turn-1" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-1">👉 Your Turn ⤵</h4>
<p>For our Learning Lab 4 case study, we focus specifically on generative processes, or micro-level mechanisms, the might help explain who school leaders select to collaborate with or engage in confidential exchanges. Review Chapter 9 of SNA and Education and report out on the findings from the ERGM analysis in response to Research Question 3 below:</p>
<ol start="3" type="1">
<li><p><strong>Does gender or some other individual attribute predicts confidential exchanges between school leaders, or does some previous relation have a stronger effect?</strong></p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
<p>Based on what you know about networks and the context so far, write another research question or hypothesis that can be tested using ERGMs:</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul>
<p>Later you’ll have a chance to empirically test it by the end of this case study.</p>
</section>
</section>
<section id="b.-load-libraries" class="level3">
<h3 class="anchored" data-anchor-id="b.-load-libraries">1b. Load Libraries</h3>
<p>Recall that <strong>packages</strong>, or libraries, are shareable collections of R code that can contain functions, data, and/or documentation and extend the functionality of R. You can always check to see which packages have already been installed and loaded into RStudio Cloud by looking at the the Files, Plots, &amp; Packages Pane in the lower right hand corner.</p>
<section id="statnet" class="level4">
<h4 class="anchored" data-anchor-id="statnet">statnet 📦</h4>
<p><img src="img/statnetlogo.png" class="img-fluid" style="width:20.0%"></p>
<p>Similar to the collection of packages contained in the {tidyverse} package, the Statnet Team <span class="citation" data-cites="handcock">(<a href="#ref-handcock" role="doc-biblioref">Pavel N. Krivitsky et al. 2003-2020</a>)</span> has developed a suite of R packages for the management, exploration, statistical analysis, simulation and vizualization of network data. The statistical modeling framework used in {statnet} relies on Exponential-family Random Graph Models (ERGMs).</p>
<p>As noted in the <a href="http://statnet.org/Workshops/ergm_tutorial.html#The_statnet_Project">statnet tutorial</a> by the same authors, the exponential-family random graph models (ERGMs) are a general class of models based in exponential-family theory for specifying the probability distribution for a set of random graphs or networks. Within this framework, one can—among other tasks:</p>
<ol type="1">
<li><p>Define a model for a network that includes covariates representing features like homophily, mutuality, triad effects, and a wide range of other structural features of interest;</p></li>
<li><p>Obtain maximum-likehood estimates for the parameters of the specified model for a given data set;</p></li>
<li><p>Test individual coefficients, assess models for convergence and goodness-of-fit and perform various types of model comparison; and</p></li>
<li><p>Simulate new networks from the underlying probability distribution implied by the fitted model.</p></li>
</ol>
</section>
<section id="your-turn-2" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-2">👉 Your Turn ⤵</h4>
<p>Let’s load the {statnet} package that we’ll be using in the Model section of our case study for bullets 1-3 above, as well as the following packages that will be using for our network analysis:</p>
<ul>
<li>tidyverse</li>
<li>readxl</li>
<li>igraph</li>
<li>tidygraph</li>
<li>ggraph</li>
<li>skimr</li>
<li>janitor</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># YOUR CODE HERE</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'igraph'

The following objects are masked from 'package:lubridate':

    %--%, union

The following objects are masked from 'package:dplyr':

    as_data_frame, groups, union

The following objects are masked from 'package:purrr':

    compose, simplify

The following object is masked from 'package:tidyr':

    crossing

The following object is masked from 'package:tibble':

    as_data_frame

The following objects are masked from 'package:stats':

    decompose, spectrum

The following object is masked from 'package:base':

    union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidygraph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'tidygraph'

The following object is masked from 'package:igraph':

    groups

The following object is masked from 'package:stats':

    filter</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'skimr'

The following object is masked from 'package:tidygraph':

    focus</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(statnet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: tergm
Loading required package: ergm
Loading required package: network

'network' 1.18.2 (2023-12-04), part of the Statnet Project
* 'news(package="network")' for changes since last version
* 'citation("network")' for citation information
* 'https://statnet.org' for help, support, and other information


Attaching package: 'network'

The following objects are masked from 'package:igraph':

    %c%, %s%, add.edges, add.vertices, delete.edges, delete.vertices,
    get.edge.attribute, get.edges, get.vertex.attribute, is.bipartite,
    is.directed, list.edge.attributes, list.vertex.attributes,
    set.edge.attribute, set.vertex.attribute


'ergm' 4.6.0 (2023-12-17), part of the Statnet Project
* 'news(package="ergm")' for changes since last version
* 'citation("ergm")' for citation information
* 'https://statnet.org' for help, support, and other information

'ergm' 4 is a major update that introduces some backwards-incompatible
changes. Please type 'news(package="ergm")' for a list of major
changes.

Loading required package: networkDynamic

'networkDynamic' 0.11.4 (2023-12-10?), part of the Statnet Project
* 'news(package="networkDynamic")' for changes since last version
* 'citation("networkDynamic")' for citation information
* 'https://statnet.org' for help, support, and other information

Registered S3 method overwritten by 'tergm':
  method                   from
  simulate_formula.network ergm

'tergm' 4.2.0 (2023-05-30), part of the Statnet Project
* 'news(package="tergm")' for changes since last version
* 'citation("tergm")' for citation information
* 'https://statnet.org' for help, support, and other information


Attaching package: 'tergm'

The following object is masked from 'package:ergm':

    snctrl

Loading required package: ergm.count

'ergm.count' 4.1.2 (2024-06-15), part of the Statnet Project
* 'news(package="ergm.count")' for changes since last version
* 'citation("ergm.count")' for citation information
* 'https://statnet.org' for help, support, and other information

Loading required package: sna
Loading required package: statnet.common

Attaching package: 'statnet.common'

The following object is masked from 'package:ergm':

    snctrl

The following objects are masked from 'package:base':

    attr, order

sna: Tools for Social Network Analysis
Version 2.7-2 created on 2023-12-05.
copyright (c) 2005, Carter T. Butts, University of California-Irvine
 For citation information, type citation("sna").
 Type help(package="sna") to get started.


Attaching package: 'sna'

The following objects are masked from 'package:igraph':

    betweenness, bonpow, closeness, components, degree, dyad.census,
    evcent, hierarchy, is.connected, neighborhood, triad.census

Loading required package: tsna

'statnet' 2019.6 (2019-06-13), part of the Statnet Project
* 'news(package="statnet")' for changes since last version
* 'citation("statnet")' for citation information
* 'https://statnet.org' for help, support, and other information

unable to reach CRAN</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="wrangle" class="level2">
<h2 class="anchored" data-anchor-id="wrangle">2. WRANGLE</h2>
<p>For our data wrangling this week, we’ll focus on working with network data stored as an adjacency matrix. Our primary goals for this section are learning how to:</p>
<ol type="a">
<li><p><strong>Import Data</strong>. In this section, we use the {readxl} package from the tidyverse to read in a matrix and node attributes.</p></li>
<li><p><strong>Dichotomize a Matrix</strong>. As described in Chapter 9, we’ll recode our edge values to 1s and 0s changing our valued matrix to a binary matrix.</p></li>
<li><p><strong>Create Network Graph</strong>. Finally, we’ll convert our matrix to an edge-list and store both our edges and node attributes as a network igraph object in preparation for analysis.</p></li>
</ol>
<section id="a.-import-data" class="level3">
<h3 class="anchored" data-anchor-id="a.-import-data">2a. Import Data</h3>
<p>One of our primary goals is to replicate the ERGM analysis from Chapter 9: Network Data and Statistical Models <span class="citation" data-cites="carolan2014">(<a href="#ref-carolan2014" role="doc-biblioref">Carolan 2014</a>)</span>. Specifically, we’ll aim to reproduce the results from Table 9.4. Results of P1 and P*Analyses for the Dichotomized and Directed School Leaders Confidential Exchanges Network Year 3.</p>
<p>To do so, we’ll need to import two Excel files from the <a href="https://studysites.sagepub.com/carolan/study/resources.htm">Social Network Analysis and Education companion site</a>. The first file contains our edges stored as a square matrix (more on this later) and the second file is a standard rectangular data frame that contains attributes for each node, i.e.&nbsp;school leaders. These files are included in the data folder of your R Studio project. A description of each file from the companion website is linked above and each data file is linked below:</p>
<ol type="1">
<li><p><a href="https://studysites.sagepub.com/carolan/study/materials/datasets/99472_ds10.xls"><strong>School Leaders Data Chapter 9_d</strong></a><strong>.</strong>&nbsp;This adjacency matrix reports on “confidential help” ties among 43 school leaders in year 3 of a three-year study. This is a directed valued (weighted) network measured on five-point scale ranging from 0 to 4, with higher values indicating more frequent collaborations (1–2 times/week). These data are used throughout Chapter 9.</p></li>
<li><p><a href="https://studysites.sagepub.com/carolan/study/materials/datasets/99472_ds11.xlsx"><strong>School Leaders Data Chapter 9_e</strong></a><strong>.</strong>&nbsp;This rectangular matrix consists of four attribute vectors for 43 school leaders. Following the first ID column, the matrix includes an efficacy score, trust score, and indicators for whether one works at the district-level and is male (1 = yes, 0 = no). These attribute variables will be used as covariates in our ERGMs later in this walkthrough.</p></li>
</ol>
<p>Since we are working with Excel files, we’ll need to use the <code>read_excel()</code> function from {readxl} tidyverse package to import our data. Let’s import the <code>School Leaders Data Chapter 9_e.xlsx</code> node file located in the <code>data/</code> folder first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>leader_nodes <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/School Leaders Data Chapter 9_e.xlsx"</span>, </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">col_types =</span> <span class="fu">c</span>(<span class="st">"text"</span>, <span class="st">"numeric"</span>, <span class="st">"numeric"</span>, <span class="st">"numeric"</span>, <span class="st">"numeric"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>leader_nodes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 43 × 5
   id    efficacy trust district_site  male
   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;
 1 1         6.06  4                1     0
 2 2         6.56  5.63             1     0
 3 3         7.39  4.63             1     0
 4 4         4.89  4                1     0
 5 5         6.06  5.75             0     1
 6 6         7.39  4.38             0     0
 7 7         5.56  3.63             0     1
 8 8         7.5   5.63             1     1
 9 9         7.67  5.25             0     0
10 10        6.64  4.78             0     0
# ℹ 33 more rows</code></pre>
</div>
</div>
<p>Note that we specified the <code>ID</code> column as “text” and the remaining columns as “numeric.” By default, the <code>readxl()</code> function would have recognized each column as numeric, but the first column indicates the “names” for each school leader and we’ll be using this column to assign names to our columns and rows for our adjacency matrix in just a bit.</p>
<section id="your-turn-3" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-3">👉 Your Turn ⤵</h4>
<p>Recall from above that our relations, or edges, are stored as a valued <a href="https://en.wikipedia.org/wiki/Adjacency_matrix">adjacency matrix</a> in which columns and rows consist of the same actors and each cell contains information about the tie between each pair of actors. In our case, the tie is a directed and valued “arc” where the value indicates the strength of the relationship.</p>
<p>Use the <code>read_excel()</code> function to import the <code>School Leaders Data Chapter 9_d.xlsx</code> file, add an argument setting the column names to <code>FALSE</code> since our file is a simple matrix with no header or column names, and assign the matrix to a variable named <code>leader_matrix</code>:</p>
<p><strong>Hint:</strong> Type <code>?read_excel</code> into the console and check the arguments section to find the name of the argument used to set column headers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#YOUR CODE HERE</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>leader_matrix <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/School Leaders Data Chapter 9_d.xlsx"</span>, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">col_names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...1`
• `` -&gt; `...2`
• `` -&gt; `...3`
• `` -&gt; `...4`
• `` -&gt; `...5`
• `` -&gt; `...6`
• `` -&gt; `...7`
• `` -&gt; `...8`
• `` -&gt; `...9`
• `` -&gt; `...10`
• `` -&gt; `...11`
• `` -&gt; `...12`
• `` -&gt; `...13`
• `` -&gt; `...14`
• `` -&gt; `...15`
• `` -&gt; `...16`
• `` -&gt; `...17`
• `` -&gt; `...18`
• `` -&gt; `...19`
• `` -&gt; `...20`
• `` -&gt; `...21`
• `` -&gt; `...22`
• `` -&gt; `...23`
• `` -&gt; `...24`
• `` -&gt; `...25`
• `` -&gt; `...26`
• `` -&gt; `...27`
• `` -&gt; `...28`
• `` -&gt; `...29`
• `` -&gt; `...30`
• `` -&gt; `...31`
• `` -&gt; `...32`
• `` -&gt; `...33`
• `` -&gt; `...34`
• `` -&gt; `...35`
• `` -&gt; `...36`
• `` -&gt; `...37`
• `` -&gt; `...38`
• `` -&gt; `...39`
• `` -&gt; `...40`
• `` -&gt; `...41`
• `` -&gt; `...42`
• `` -&gt; `...43`</code></pre>
</div>
</div>
<p>Use the code chunk below to inspect the matrix you just imported and answer the questions that follow:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>leader_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 43 × 43
    ...1  ...2  ...3  ...4  ...5  ...6  ...7  ...8  ...9 ...10 ...11 ...12 ...13
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1     0     0     0     0     0     0     0     0     0     0     0     0     0
 2     0     0     0     0     0     0     0     0     0     0     0     0     0
 3     3     1     0     1     1     1     1     2     1     1     1     1     1
 4     1     0     0     0     0     0     0     0     0     0     0     0     0
 5     0     0     0     0     0     0     1     0     3     0     0     0     0
 6     0     0     0     0     0     0     0     0     0     0     0     0     0
 7     2     1     1     1     1     1     4     1     1     3     1     1     1
 8     1     1     4     1     1     1     1     0     2     3     1     1     1
 9     1     0     0     0     4     0     0     1     0     0     0     0     0
10     1     1     3     1     1     1     4     4     1     0     3     1     1
# ℹ 33 more rows
# ℹ 30 more variables: ...14 &lt;dbl&gt;, ...15 &lt;dbl&gt;, ...16 &lt;dbl&gt;, ...17 &lt;dbl&gt;,
#   ...18 &lt;dbl&gt;, ...19 &lt;dbl&gt;, ...20 &lt;dbl&gt;, ...21 &lt;dbl&gt;, ...22 &lt;dbl&gt;,
#   ...23 &lt;dbl&gt;, ...24 &lt;dbl&gt;, ...25 &lt;dbl&gt;, ...26 &lt;dbl&gt;, ...27 &lt;dbl&gt;,
#   ...28 &lt;dbl&gt;, ...29 &lt;dbl&gt;, ...30 &lt;dbl&gt;, ...31 &lt;dbl&gt;, ...32 &lt;dbl&gt;,
#   ...33 &lt;dbl&gt;, ...34 &lt;dbl&gt;, ...35 &lt;dbl&gt;, ...36 &lt;dbl&gt;, ...37 &lt;dbl&gt;,
#   ...38 &lt;dbl&gt;, ...39 &lt;dbl&gt;, ...40 &lt;dbl&gt;, ...41 &lt;dbl&gt;, ...42 &lt;dbl&gt;, …</code></pre>
</div>
</div>
<ol type="1">
<li><p>Is our network a square matrix? What does this tell you about the number of nodes in our network?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>Does our network contain self-loops? How do you know?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>What do the values in each cell of our matrix indicate?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
</section>
</section>
<section id="b.-dichotomize-matrix" class="level3">
<h3 class="anchored" data-anchor-id="b.-dichotomize-matrix">2b. Dichotomize Matrix</h3>
<p>Since one of our goals is a crude replication of the analysis demonstrated in Chapter 9, and since working with “valued networks” is a little more complex than binary networks that simply indicate the presence or absence of a tie, we will need to “dichotomize” our matrix. In practice this simply entails converting our valued matrix to a binary matrix with cells containing just 1s or 0s.</p>
<p>In their article, <em>Valued Ties Tell Fewer Lies: Why Not To Dichotomize Network Edges With Thresholds</em>, <span class="citation" data-cites="thomas2011valued">Thomas and Blitzstein (<a href="#ref-thomas2011valued" role="doc-biblioref">2011</a>)</span> highlight several reasons why the dichotomization procedure is appealing in an investigation aside from convenience and simplicity:</p>
<ol type="1">
<li><p><strong>Use of Exclusively Binary Methods.</strong> Several classes of models have been designed to incorporate binary information directly, including the exponential random graph model.</p></li>
<li><p><strong>Ease of Input and Data Collection.</strong> The need to classify continuously-valued quantities into a set of discrete groups is widespread throughout all of science and technology, particularly because of the associated need to make clear decisions based on this information.</p></li>
<li><p><strong>Ease of Output in Graphical Representations.</strong> The visual appeal of graphs and networks has contributed to much of the field’s attention in the past decade. When plotting a graphical structure, a clever choice of threshold can illuminate which nodes are most central, which connections the most vital.</p></li>
<li><p><strong>Sparsity of Structure.</strong> In data where there are very few natural zeroes (if any), di- chotomization provides a way to select for a small number of connections which are thought to be of the greatest importance to the system, or to nominate a number of ties for more in-depth study.</p></li>
<li><p><strong>Binning To Address Nonlinearity and Reduce Noise.</strong> If there is a nonlinear relationship in the data, binning the data into distinct ordinal categories has many advantages, namely, the reduction of total mean-squared error, and a corresponding increase in power for detecting a true non-zero relationship over an improperly specified linear analysis.</p></li>
</ol>
<p>As the title of their article suggests, however, Thomas and Blitzstein argue that the motivations for dichotomization should be revisited as dichotomization produces a range of problematic issues.</p>
<p>With that in mind, and before we can dichotomize our “matrix,” we first need to convert it to a matrix object recognized by R using the <code>as.matrix()</code> function. We can then check to data format of our <code>leader_matrix</code> using the <code>class()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>leader_matrix <span class="ot">&lt;-</span> leader_matrix <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>()</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(leader_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "matrix" "array" </code></pre>
</div>
</div>
<p>Both the collaboration and confidential help network data were dichotomized by recoding values originally coded as a 3 and 4 recoded to 1, indicating the presence of a directed tie for both relations, and zero otherwise.</p>
<p>To dichotomize our our matrix, the following code will “assign” 0’s to all values in our matrix that are less than or equal to 2, and 1’s to all values that are greater the or equal to 3:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>leader_matrix[leader_matrix <span class="sc">&lt;=</span> <span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>leader_matrix[leader_matrix <span class="sc">&gt;=</span> <span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="add-row-and-column-names" class="level4">
<h4 class="anchored" data-anchor-id="add-row-and-column-names">Add Row and Column Names</h4>
<p>Before we can convert to an edge-list, we will also need to add the names of our nodes to the columns and rows of our matrix. These are stored in the <code>ID</code> column of our <code>leader_node</code> data frame. We can use the <code>$</code> operator to select these names and assign to our <code>leader_matrix</code> using the <code>rownames()</code> and <code>colnames()</code> functions respectively:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(leader_matrix) <span class="ot">&lt;-</span> leader_nodes<span class="sc">$</span>id</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(leader_matrix) <span class="ot">&lt;-</span> leader_nodes<span class="sc">$</span>id</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>leader_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
1  0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
2  0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
3  1 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1
4  0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  1
5  0 0 0 0 0 0 0 0 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
6  0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
7  0 0 0 0 0 0 1 0 0  1  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0
8  0 0 1 0 0 0 0 0 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  1  1
9  0 0 0 0 1 0 0 0 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
10 0 0 1 0 0 0 1 1 0  0  1  0  0  0  0  0  0  1  0  1  0  0  0  0  0  0  0  0
11 0 0 0 0 0 0 0 0 0  1  0  0  0  0  0  0  0  0  0  0  1  0  1  0  0  0  0  0
12 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
13 0 0 0 0 0 0 0 1 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
14 0 0 0 0 0 0 0 0 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
15 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0
16 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0
17 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  1  0  0
18 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
19 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0
20 0 0 0 0 0 0 1 0 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
21 1 0 0 0 0 0 0 0 0  0  1  1  0  0  1  0  0  0  0  0  1  0  0  0  0  0  0  0
22 0 0 0 0 0 0 0 1 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  1
23 0 0 0 0 1 0 0 0 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
24 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0
25 0 0 1 0 0 0 0 1 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
26 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0
27 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0
28 1 1 1 1 0 1 0 1 1  1  0  0  1  0  0  0  0  1  0  0  1  1  0  0  1  0  1  1
29 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
30 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
31 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0
32 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0
33 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0
34 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  1  0  0  0  1  0  0  0  0  0  1
35 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0
36 1 0 1 1 0 0 0 1 0  0  0  0  0  0  0  1  0  1  0  0  0  0  0  0  0  1  1  1
37 0 0 1 0 0 0 0 0 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
38 1 0 1 0 0 0 0 1 0  0  1  0  0  0  0  0  0  1  0  0  0  1  0  0  0  1  1  1
39 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
40 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
41 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
42 0 0 0 0 0 0 0 0 1  0  0  0  0  0  1  0  0  0  0  0  0  0  0  1  0  0  1  0
43 0 0 0 0 1 0 0 1 0  0  0  0  0  0  1  0  0  1  0  0  1  1  1  0  0  0  0  0
   29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
1   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
2   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
3   0  0  0  0  0  0  0  1  0  1  0  0  0  0  0
4   0  0  0  0  0  1  0  1  0  0  0  0  0  0  0
5   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
6   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
7   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
8   0  0  0  0  0  0  0  0  1  1  0  0  0  0  0
9   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
10  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0
11  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0
12  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
13  0  0  0  0  0  0  1  0  0  0  0  0  0  1  0
14  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0
15  0  0  0  0  0  0  0  0  0  0  1  0  0  1  1
16  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
18  1  0  0  0  0  1  0  0  0  0  0  0  0  0  0
19  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0
20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
21  0  0  0  0  1  0  1  0  1  1  0  0  0  0  1
22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
24  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0
25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
26  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0
27  0  0  0  1  0  0  0  0  0  0  0  0  0  1  0
28  1  0  0  1  0  1  0  1  1  1  0  0  0  0  0
29  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
31  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
32  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
33  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
34  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
35  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
36  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0
37  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0
38  0  0  0  0  1  1  0  1  1  0  1  0  0  0  1
39  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
41  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0
42  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1
43  0  0  0  1  1  1  0  0  1  0  0  0  0  1  0</code></pre>
</div>
</div>
</section>
</section>
<section id="c.-create-network-with-attributes" class="level3">
<h3 class="anchored" data-anchor-id="c.-create-network-with-attributes">2c. Create Network with Attributes</h3>
<p>Recall that edge-lists contain a row for each dyad consisting of at minimum two columns with the name of each actor, and which conveniently can also contain other information or attributes about the relationship such as edge weight, timestamps, or other contextual information as demonstrated in Learning Lab 1.</p>
<p>Edge-lists also have the advantage of being easier to work with when using network packages in R.</p>
<section id="get-edges" class="level4">
<h4 class="anchored" data-anchor-id="get-edges">Get Edges</h4>
<p>The {igraph} package introduced in Learning Lab 1 has a convenient <code>get.data.frame()</code> function for extracting an edge list from a matrix, but first we need to convert our matrix to an igraph network object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>adjacency_matrix <span class="ot">&lt;-</span> <span class="fu">graph.adjacency</span>(leader_matrix,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">diag =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `graph.adjacency()` was deprecated in igraph 2.0.0.
ℹ Please use `graph_from_adjacency_matrix()` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(adjacency_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "igraph"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>adjacency_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>IGRAPH cfe93fb DN-- 43 143 -- 
+ attr: name (v/c)
+ edges from cfe93fb (vertex names):
 [1] 3 -&gt;1  3 -&gt;27 3 -&gt;28 3 -&gt;36 3 -&gt;38 4 -&gt;16 4 -&gt;28 4 -&gt;34 4 -&gt;36 5 -&gt;9 
[11] 7 -&gt;10 7 -&gt;20 8 -&gt;3  8 -&gt;10 8 -&gt;25 8 -&gt;27 8 -&gt;28 8 -&gt;37 8 -&gt;38 9 -&gt;5 
[21] 9 -&gt;14 10-&gt;3  10-&gt;7  10-&gt;8  10-&gt;11 10-&gt;18 10-&gt;20 10-&gt;38 11-&gt;10 11-&gt;21
[31] 11-&gt;23 11-&gt;35 13-&gt;8  13-&gt;35 13-&gt;42 14-&gt;37 15-&gt;21 15-&gt;39 15-&gt;42 15-&gt;43
[41] 16-&gt;22 17-&gt;26 18-&gt;29 18-&gt;34 19-&gt;31 20-&gt;7  20-&gt;10 21-&gt;1  21-&gt;11 21-&gt;12
[51] 21-&gt;15 21-&gt;33 21-&gt;35 21-&gt;37 21-&gt;38 21-&gt;43 22-&gt;8  22-&gt;16 22-&gt;28 23-&gt;5 
[61] 23-&gt;11 24-&gt;27 24-&gt;42 25-&gt;3  25-&gt;8  26-&gt;17 26-&gt;41 27-&gt;24 27-&gt;32 27-&gt;42
[71] 28-&gt;1  28-&gt;2  28-&gt;3  28-&gt;4  28-&gt;6  28-&gt;8  28-&gt;9  28-&gt;10 28-&gt;13 28-&gt;18
+ ... omitted several edges</code></pre>
</div>
</div>
<p>Note that we included the <code>diag = FALSE</code> argument which converts all values along the diagonal to 0s, thereby removing self-loops. I believe they may have been included when calculating the network descriptives included in Table 9.1, and our own descriptives may not match exactly, but we’ll need to remove these from our network for the ERGM analysis so this will save us a step.</p>
<p>Now we can use the <code>get.data.frame()</code> function to covert our matrix to a standard edge-list:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>leader_edges <span class="ot">&lt;-</span> <span class="fu">get.data.frame</span>(adjacency_matrix) <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">from =</span> <span class="fu">as.character</span>(from)) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">to =</span> <span class="fu">as.character</span>(to))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `get.data.frame()` was deprecated in igraph 2.0.0.
ℹ Please use `as_data_frame()` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>leader_edges</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    from to
1      3  1
2      3 27
3      3 28
4      3 36
5      3 38
6      4 16
7      4 28
8      4 34
9      4 36
10     5  9
11     7 10
12     7 20
13     8  3
14     8 10
15     8 25
16     8 27
17     8 28
18     8 37
19     8 38
20     9  5
21     9 14
22    10  3
23    10  7
24    10  8
25    10 11
26    10 18
27    10 20
28    10 38
29    11 10
30    11 21
31    11 23
32    11 35
33    13  8
34    13 35
35    13 42
36    14 37
37    15 21
38    15 39
39    15 42
40    15 43
41    16 22
42    17 26
43    18 29
44    18 34
45    19 31
46    20  7
47    20 10
48    21  1
49    21 11
50    21 12
51    21 15
52    21 33
53    21 35
54    21 37
55    21 38
56    21 43
57    22  8
58    22 16
59    22 28
60    23  5
61    23 11
62    24 27
63    24 42
64    25  3
65    25  8
66    26 17
67    26 41
68    27 24
69    27 32
70    27 42
71    28  1
72    28  2
73    28  3
74    28  4
75    28  6
76    28  8
77    28  9
78    28 10
79    28 13
80    28 18
81    28 21
82    28 22
83    28 25
84    28 27
85    28 29
86    28 32
87    28 34
88    28 36
89    28 37
90    28 38
91    31 19
92    32 24
93    33 21
94    34 18
95    34 22
96    34 28
97    34 29
98    35 21
99    36  1
100   36  3
101   36  4
102   36  8
103   36 16
104   36 18
105   36 26
106   36 27
107   36 28
108   36 34
109   37  3
110   37 14
111   37 38
112   38  1
113   38  3
114   38  8
115   38 11
116   38 18
117   38 22
118   38 26
119   38 27
120   38 28
121   38 33
122   38 34
123   38 36
124   38 37
125   38 39
126   38 43
127   42  9
128   42 15
129   42 24
130   42 27
131   42 43
132   43  5
133   43  8
134   43 15
135   43 18
136   43 21
137   43 22
138   43 23
139   43 32
140   43 33
141   43 34
142   43 37
143   43 42</code></pre>
</div>
</div>
</section>
<section id="your-turn-4" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-4">👉 Your Turn ⤵</h4>
<p>Recall from Learning Lab 2 that we introduced the {tidygraph} package for preparing and summarizing our Twitter network. Tidygraph includes the full functionality of&nbsp;<code>igraph</code>&nbsp;in a tidy API giving you access to almost all of the&nbsp;<code>dplyr</code>&nbsp;verbs plus a few more, developed for use with relational data.</p>
<p>Similar to Learning Lab 2, use the <code>tbl_graph()</code> function to convert our <code>leader_edges</code> and <code>leader_nodes</code> data frames into a network graph object, by including the following arguments and supplying the appropriate code:</p>
<ul>
<li><p><code>edges =</code> expects a data frame, in our case <code>leader_edges</code>, containing information about the edges in the graph. The nodes of each edge must either be in a <code>to</code> and <code>from</code> column, or in the two first columns like the data frame we provided.</p></li>
<li><p><code>nodes =</code> expects a data frame, in our case <code>leader_nodes</code>, containing information about the nodes in the graph. If <code>to</code> and/or <code>from</code> are characters or names, like in our data frames, then they will be matched to the column named according to <code>node_key</code> in nodes, if it exists, or matched to the first column in the node list.</p></li>
<li><p><code>directed =</code> specifies whether the constructed graph be directed.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># YOUR CODE HERE</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>leader_graph <span class="ot">&lt;-</span> <span class="fu">tbl_graph</span>(<span class="at">edges =</span> leader_edges,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">nodes =</span> leader_nodes,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">directed =</span> <span class="cn">TRUE</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>leader_graph</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tbl_graph: 43 nodes and 143 edges
#
# A directed simple graph with 4 components
#
# Node Data: 43 × 5 (active)
   id    efficacy trust district_site  male
   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;
 1 1         6.06  4                1     0
 2 2         6.56  5.63             1     0
 3 3         7.39  4.63             1     0
 4 4         4.89  4                1     0
 5 5         6.06  5.75             0     1
 6 6         7.39  4.38             0     0
 7 7         5.56  3.63             0     1
 8 8         7.5   5.63             1     1
 9 9         7.67  5.25             0     0
10 10        6.64  4.78             0     0
# ℹ 33 more rows
#
# Edge Data: 143 × 2
   from    to
  &lt;int&gt; &lt;int&gt;
1     3     1
2     3    27
3     3    28
# ℹ 140 more rows</code></pre>
</div>
</div>
<p>Congrats! You made it to the end of data wrangling section and are ready to start analysis!</p>
</section>
</section>
</section>
<section id="explore" class="level2">
<h2 class="anchored" data-anchor-id="explore">3. EXPLORE</h2>
<p>In Section 3, we use the {tidygraph} package for retrieving network descriptives and the {ggraph} package to create a network visualization to help illustrate these metrics. Specifically, in this section we will:</p>
<ol type="a">
<li><p><strong>Examine Basic Descriptives</strong>. We focus primarily on actors and edges in this walkthrough, including whether or not ties were reciprocated and node degree, an important and fairly intuitive measure of centrality.</p></li>
<li><p><strong>Make a Sociogram</strong>. Finally, we wrap up the explore phases by learning to plot a network and tweak key elements like the size, shape, and position of nodes and edges to better at communicating key findings.</p></li>
</ol>
<section id="a.-examine-descriptives" class="level3">
<h3 class="anchored" data-anchor-id="a.-examine-descriptives">3a. Examine Descriptives</h3>
<p>As noted in SNA and Education <span class="citation" data-cites="carolan2014">(<a href="#ref-carolan2014" role="doc-biblioref">Carolan 2014</a>)</span>, many analyses of social networks are primarily descriptive and aim to either represent the network’s underlying social structure through data-reduction techniques or to characterize network properties through network measures.</p>
<p>In the analyses described in Chapter 9, descriptives were limited to the mean and standard deviation for: in-degree, out-degree, trust and efficacy measures. The proportion of male leaders was also reported. For section 3a, let’s see if we can reproduce these descriptives.</p>
<section id="calculate-node-degree" class="level4">
<h4 class="anchored" data-anchor-id="calculate-node-degree">Calculate Node Degree</h4>
<p>Recall that <strong>degree</strong> is the number of ties to and from an ego, or in the case of a “simple graph” like ours, degree is simply the number of people to whom someone is connected. In a directed network, <strong>in-degree</strong> is the number of connections or ties received, whereas <strong>out-degree</strong> is the number of connections or ties sent.</p>
<p>The <code>activate()</code> function from the {tidygraph} package allows us to treat the nodes in our network object as if they were a standard data frame to which we can then apply tidyverse functions such as <code>select()</code>, <code>filter()</code>, and <code>mutate()</code>.</p>
<p>We can use the <code>mutate()</code> functions to create new variables for nodes such as measures of degree, in-degree, and out-degree using the <code>centrality_degree()</code> function in the {tidygraph} package.</p>
<p>Run the following code to add in- and out-degree measures to each of our nodes and examine the output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>leader_measures <span class="ot">&lt;-</span> leader_graph <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(nodes) <span class="sc">|&gt;</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">in_degree =</span> <span class="fu">centrality_degree</span>(<span class="at">mode =</span> <span class="st">"in"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">out_degree =</span> <span class="fu">centrality_degree</span>(<span class="at">mode =</span> <span class="st">"out"</span>))</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>leader_measures</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tbl_graph: 43 nodes and 143 edges
#
# A directed simple graph with 4 components
#
# Node Data: 43 × 7 (active)
   id    efficacy trust district_site  male in_degree out_degree
   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1 1         6.06  4                1     0         5          0
 2 2         6.56  5.63             1     0         1          0
 3 3         7.39  4.63             1     0         7          5
 4 4         4.89  4                1     0         2          4
 5 5         6.06  5.75             0     1         3          1
 6 6         7.39  4.38             0     0         1          0
 7 7         5.56  3.63             0     1         2          2
 8 8         7.5   5.63             1     1         8          7
 9 9         7.67  5.25             0     0         3          2
10 10        6.64  4.78             0     0         5          7
# ℹ 33 more rows
#
# Edge Data: 143 × 2
   from    to
  &lt;int&gt; &lt;int&gt;
1     3     1
2     3    27
3     3    28
# ℹ 140 more rows</code></pre>
</div>
</div>
</section>
<section id="your-turn-5" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-5">👉 Your Turn ⤵</h4>
<p>We now see that, in addition to the previously included attributes <code>trust</code> and <code>efficacy</code>, in-degree and out-degree measures have been added to the nodes in our network. But what if we also want to know to total number of “alters” each “ego” is connected to, i.e.&nbsp;the total number of individuals each school leader are connected to?</p>
<p>Modify the code below to calculate <code>degree</code> for each school leader in our network. <strong>Hint:</strong> <code>centrality_degree</code> is a wrapper for <code>igraph::degree()</code> and the <code>mode =</code> argument can be found in the corresponding help documentation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>leader_measures <span class="ot">&lt;-</span> leader_graph <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(nodes) <span class="sc">|&gt;</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">degree =</span> <span class="fu">centrality_degree</span>(<span class="at">mode =</span> <span class="st">"all"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">in_degree =</span> <span class="fu">centrality_degree</span>(<span class="at">mode =</span> <span class="st">"in"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">out_degree =</span> <span class="fu">centrality_degree</span>(<span class="at">mode =</span> <span class="st">"out"</span>))</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>leader_measures</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tbl_graph: 43 nodes and 143 edges
#
# A directed simple graph with 4 components
#
# Node Data: 43 × 8 (active)
   id    efficacy trust district_site  male degree in_degree out_degree
   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1 1         6.06  4                1     0      5         5          0
 2 2         6.56  5.63             1     0      1         1          0
 3 3         7.39  4.63             1     0     12         7          5
 4 4         4.89  4                1     0      6         2          4
 5 5         6.06  5.75             0     1      4         3          1
 6 6         7.39  4.38             0     0      1         1          0
 7 7         5.56  3.63             0     1      4         2          2
 8 8         7.5   5.63             1     1     15         8          7
 9 9         7.67  5.25             0     0      5         3          2
10 10        6.64  4.78             0     0     12         5          7
# ℹ 33 more rows
#
# Edge Data: 143 × 2
   from    to
  &lt;int&gt; &lt;int&gt;
1     3     1
2     3    27
3     3    28
# ℹ 140 more rows</code></pre>
</div>
</div>
</section>
<section id="summarize-node-measures" class="level4">
<h4 class="anchored" data-anchor-id="summarize-node-measures">Summarize Node Measures</h4>
<p>We can also use the <code>activate()</code> function combined with the <code>as_tibble()</code> function introduced in our previous Learning Lab to extract our new measures to a separate data frame we’ll call <code>node_measures</code> so we can inspect our nodes individually and later use to calculate some summary stats:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>node_measures <span class="ot">&lt;-</span> leader_measures <span class="sc">|&gt;</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(nodes) <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>()</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>node_measures</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 43 × 8
   id    efficacy trust district_site  male degree in_degree out_degree
   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1 1         6.06  4                1     0      5         5          0
 2 2         6.56  5.63             1     0      1         1          0
 3 3         7.39  4.63             1     0     12         7          5
 4 4         4.89  4                1     0      6         2          4
 5 5         6.06  5.75             0     1      4         3          1
 6 6         7.39  4.38             0     0      1         1          0
 7 7         5.56  3.63             0     1      4         2          2
 8 8         7.5   5.63             1     1     15         8          7
 9 9         7.67  5.25             0     0      5         3          2
10 10        6.64  4.78             0     0     12         5          7
# ℹ 33 more rows</code></pre>
</div>
</div>
<p>Now let’s view some basic summary statistics for each of the variables using the handy <code>summary()</code> function included in the R {base} package and the <code>skim()</code> functions from the {skimr} package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(node_measures)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      id               efficacy         trust       district_site   
 Length:43          Min.   :4.610   Min.   :3.630   Min.   :0.0000  
 Class :character   1st Qu.:5.670   1st Qu.:4.130   1st Qu.:0.0000  
 Mode  :character   Median :6.780   Median :4.780   Median :0.0000  
                    Mean   :6.649   Mean   :4.783   Mean   :0.4186  
                    3rd Qu.:7.470   3rd Qu.:5.440   3rd Qu.:1.0000  
                    Max.   :8.500   Max.   :5.880   Max.   :1.0000  
      male            degree         in_degree       out_degree    
 Min.   :0.0000   Min.   : 0.000   Min.   :0.000   Min.   : 0.000  
 1st Qu.:0.0000   1st Qu.: 3.000   1st Qu.:2.000   1st Qu.: 1.000  
 Median :0.0000   Median : 4.000   Median :3.000   Median : 2.000  
 Mean   :0.4419   Mean   : 6.651   Mean   :3.326   Mean   : 3.326  
 3rd Qu.:1.0000   3rd Qu.: 9.500   3rd Qu.:5.000   3rd Qu.: 4.000  
 Max.   :1.0000   Max.   :27.000   Max.   :8.000   Max.   :20.000  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(node_measures)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">node_measures</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">43</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">id</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">efficacy</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.65</td>
<td style="text-align: right;">1.10</td>
<td style="text-align: right;">4.61</td>
<td style="text-align: right;">5.67</td>
<td style="text-align: right;">6.78</td>
<td style="text-align: right;">7.47</td>
<td style="text-align: right;">8.50</td>
<td style="text-align: left;">▅▅▃▇▃</td>
</tr>
<tr class="even">
<td style="text-align: left;">trust</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.78</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">3.63</td>
<td style="text-align: right;">4.13</td>
<td style="text-align: right;">4.78</td>
<td style="text-align: right;">5.44</td>
<td style="text-align: right;">5.88</td>
<td style="text-align: left;">▆▆▅▆▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">district_site</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▆</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">degree</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.65</td>
<td style="text-align: right;">5.80</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">9.50</td>
<td style="text-align: right;">27.00</td>
<td style="text-align: left;">▇▃▂▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">in_degree</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.33</td>
<td style="text-align: right;">2.12</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">8.00</td>
<td style="text-align: left;">▅▇▂▅▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">out_degree</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.33</td>
<td style="text-align: right;">4.26</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">20.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>It looks like our summary stats for Year 3 confidential exchanges network and attribute data are pretty close to those reported in Table 9.1 copied from <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span>. For example, our mean total efficacy and trust scores were 6.65 and 4.78 respectively, compared to 6.64 and 4.77 as reported in Chapter 9.</p>
<p><img src="img/table-9-1.jpg" class="img-fluid" style="width:80.0%"></p>
<p>The average in/out-degree for our school leaders data is 3.26, however, which is a little lower than that reported by Carolyn. Again, this is likely a function of our removal of self-loops. To test this theory, we could simply change the <code>diag = FALSE</code> argument added to the <code>graph.adjacency()</code> function above to <code>TRUE</code> to include self-loops and then try rerunning all the code above.</p>
</section>
<section id="schooldistrict-level-stats" class="level4">
<h4 class="anchored" data-anchor-id="schooldistrict-level-stats">School/District-Level Stats</h4>
<p>Since we are now working with a standard data frame, we can also apply <a href="https://dplyr.tidyverse.org/index.html">{dyplr}</a> functions like <a href="https://dplyr.tidyverse.org/reference/group_by.html"><code>group_by()</code></a> and <a href="https://dplyr.tidyverse.org/reference/summarise.html"><code>summarise()</code></a> to calculate basic summary stats such as counts, mean, and standard deviation as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>node_measures <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(district_site) <span class="sc">|&gt;</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean =</span> <span class="fu">mean</span>(in_degree), </span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(in_degree)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>            )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  district_site     n  mean    sd
          &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
1             0    25  2.36  1.58
2             1    18  4.67  2.09</code></pre>
</div>
</div>
<p>We see that our measures are pretty close, but not an exact match. Again, this is likely due to the self-loops we excluded. For example, our average in-degree for district-level (coded “1”) and school-level (coded “0”) leaders is 4.66 and 2.36 respectively, but reported as 4.72 and 2.64 by <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span>.</p>
</section>
<section id="your-turn-6" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-6">👉 Your Turn ⤵</h4>
<p>Use the code chunk below and additional chunks if needed to try and replicate the school and district level findings for out-degree, trust and efficacy measures.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>node_measures <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(district_site) <span class="sc">|&gt;</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean =</span> <span class="fu">mean</span>(out_degree), </span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(out_degree)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>            )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  district_site     n  mean    sd
          &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
1             0    25  2.44  3.01
2             1    18  4.56  5.41</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>node_measures <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(district_site) <span class="sc">|&gt;</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean =</span> <span class="fu">mean</span>(trust), </span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(trust)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>            )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  district_site     n  mean    sd
          &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
1             0    25  4.90 0.719
2             1    18  4.62 0.688</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>node_measures <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(district_site) <span class="sc">|&gt;</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean =</span> <span class="fu">mean</span>(efficacy), </span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(efficacy)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>            )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  district_site     n  mean    sd
          &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
1             0    25  7.02 0.953
2             1    18  6.13 1.12 </code></pre>
</div>
</div>
<p>How close your result to those reported by Carolyn Table 9.1?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul>
</section>
</section>
<section id="b.-visualize-network-properties" class="level3">
<h3 class="anchored" data-anchor-id="b.-visualize-network-properties">3b. Visualize Network Properties</h3>
<p>In Chapter 9, <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span> depicts a directed and dichotomous sociogram of the <strong>collaboration</strong> network for year 3 is shown in .</p>
<p><img src="img/figure-9-1.jpg" class="img-fluid" style="width:80.0%"></p>
<section id="your-turn-7" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-7">👉 Your Turn ⤵</h4>
<p>Try creating a <strong>Year 3 Confidential Exchange Network</strong> by modifying the code below and tweaking the included function/arguments or adding new ones for <a href="https://ggraph.data-imaginist.com/articles/Layouts.html">layouts</a>, <a href="https://ggraph.data-imaginist.com/articles/Nodes.html">nodes</a>, and <a href="https://ggraph.data-imaginist.com/articles/Edges.html">edges</a> to make our plot either more “aesthetically pleasing” or more purposeful in what it’s trying to communicate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#YOUR CODE HERE</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>leader_measures <span class="sc">|&gt;</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggraph</span>(<span class="at">layout =</span> <span class="st">"fr"</span>) <span class="sc">+</span> </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_node_point</span>() <span class="sc">+</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_edge_link</span>() <span class="sc">+</span> </span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_graph</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/improve-sociogram-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>After you are satisfied with your sociogram, answer the following questions?</p>
<ol type="1">
<li><p>How is the Year 3 confidential exchange network similar to the collaboration network? How is it different?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
<p>Congrats! You made it to the end of the Explore section and are ready to learn a little ab out modeling network selection processes using ERGMs! Before proceeding further, knit your document and check to see if you encounter any errors.</p>
</section>
</section>
</section>
<section id="model" class="level2">
<h2 class="anchored" data-anchor-id="model">4. MODEL</h2>
<p>Recall from <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span> that network models and the questions they are designed to address are categorized into three different analytical emphases:</p>
<ol type="1">
<li><p>Relationship-level models that focus on the ties between actors in complete networks;</p></li>
<li><p>Models that predict individual actors’ attributes; and,</p></li>
<li><p>Actor-level models that emphasize the differences within and among groups of actors within a complete network.</p></li>
</ol>
<p><strong>Exponential Random Graph Models</strong> fall into category 1 and are relationship-level models that focus on how formation of dyadic ties within a complete relational network can be explained by both structural and attribute variables. ERGMs provide a means to compare whether a network’s observed structural properties occur more frequently than you could expect from chance alone. More specifically, ERGMS provide a way to determine whether observed network properties like reciprocity and assortativity occur by chance as a result of other network properties.</p>
<p>While the technical aspects of estimating ERGMs are complex, their interpretation is pretty straightforward. In this section we are interested exploring how these models can be used to make inferences about the social processes at work in the School Leaders data. For example, in this section we will explore the following questions posed in Chapter 9:</p>
<ol type="1">
<li><p><strong>Reciprocity.</strong> If one school leader turns to another to discuss something confidential, is the latter likely to reciprocate?</p></li>
<li><p><strong>Transitivity.</strong> Are school leaders more likely to confide in someone if they both confide in the same school leader?</p></li>
<li><p><strong>Attribute Effect.</strong> Do a leader’s gender and efficacy score, predict a confidential exchange between two leaders?</p></li>
</ol>
<section id="a.-loading-network-data" class="level3">
<h3 class="anchored" data-anchor-id="a.-loading-network-data">4a. Loading Network Data</h3>
<p>As we’ve discovered in previous learning labs, network data can come in many different forms — ties can be stored as edgelists or matrices, saved as .csv or excel files, and converted to a variety of network R objects. Attributes for the nodes, ties and dyads can also take various forms and be added in various ways to objects in R. For the {ergm} package, however, data will need to be transformed into a object of the class “network” — the format that statnet uses to store and work with network data.</p>
<p>Fortunately, we have already prepared our data for quick conversion to a <code>network</code> object and can supply just a couple arguments to the <code>as.network()</code> function from the {network} package used by statnet:</p>
<ul>
<li><p><code>x =</code> a matrix giving the network structure in adjacency, incidence, or edgelist form;</p></li>
<li><p><code>vertices</code> = an optional<code>data.frame</code> containing the vertex attributes. The first column is assigned to the <code>"vertex.names"</code> and additional columns are used to set vertex attributes using their column names.</p></li>
</ul>
<p>Similar to the <code>tbl_graph</code> function from {tidygraph} that we used above, let’s add our <code>leader_edges</code> edge-list and our <code>leader_nodes</code> data frame as the <code>x =</code> and <code>vertices =</code> arguments in the <code>as.network()</code> function and assign to a new object called <code>leader_network</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>leader_network <span class="ot">&lt;-</span> <span class="fu">as.network</span>(leader_edges,</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">vertices =</span> leader_nodes)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>leader_network</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Network attributes:
  vertices = 43 
  directed = TRUE 
  hyper = FALSE 
  loops = FALSE 
  multiple = FALSE 
  bipartite = FALSE 
  total edges= 143 
    missing edges= 0 
    non-missing edges= 143 

 Vertex attribute names: 
    district_site efficacy male trust vertex.names 

No edge attributes</code></pre>
</div>
</div>
<p>Note that we could also have supplied our <code>leader_matrix</code> as the first argument, but using and edgelist vastly simplifies the process of adding node attributes.</p>
<p>Let’s also check the be sure that our <code>leader_network</code> is indeed a <code>network</code> object by using the <code>class()</code> function to identify object type:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(leader_network)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "network"</code></pre>
</div>
</div>
<p>So far so good! Let’s start building our first ERGM model!</p>
</section>
<section id="b.-estimate-the-ergm" class="level3">
<h3 class="anchored" data-anchor-id="b.-estimate-the-ergm">4b. Estimate the ERGM</h3>
<p>We’ll begin by running a simple model both to demonstrate the most commonly used functions for ERGMs and also to replicate the approach in Chapter 9 of <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span>.</p>
<p>The syntax for specifying a model in the <code>ergm</code>&nbsp;package follows R’s standard formula convention: <code>my_network ~ ergm_term_1 + ergm_term_2 + ergm_term_3</code> and so forth.</p>
<p>This syntax is used for both the&nbsp;<code>summary</code>&nbsp;and&nbsp;<code>ergm</code>&nbsp;functions.</p>
<ul>
<li><p>The&nbsp;<code>summary</code>&nbsp;function simply returns the numerical values of the network statistics in the model.</p></li>
<li><p>The&nbsp;<code>ergm</code>&nbsp;function estimates the model with those statistics.</p></li>
</ul>
<p>As noted by the <a href="http://statnet.org/Workshops/ergm_tutorial.html#The_summary_and_ergm_functions,_and_supporting_functions">Statnet Development Team</a>:</p>
<blockquote class="blockquote">
<p>It is good practice to run a&nbsp;<code>summmary</code> command on any model before fitting it with <code>ergm</code>. This is the ERGM equivalent of performing some descriptive analysis on your covariates. This can help you make sure you understand what the term represents, and it can help to flag potential problems that will lead to poor modeling results.</p>
</blockquote>
<section id="network-structure-parameters" class="level4">
<h4 class="anchored" data-anchor-id="network-structure-parameters">Network Structure Parameters</h4>
<p>Let’s start with with a simple model similar to the P<sub>1</sub> model in Table 9.4. This model contains the required ergm-term <strong><code>edges</code></strong> that represents the total number of edges in the network, and the ergm-term <strong><code>mutual</code></strong> that examines the tendency for ties to be reciprocated, i.e.&nbsp;“mutuality”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(leader_network <span class="sc">~</span> edges <span class="sc">+</span> mutual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> edges mutual 
   143     36 </code></pre>
</div>
</div>
<p>We see from our summary that our <code>leader_network</code> consists of 143 edges and 36 reciprocated dyads.</p>
<p>Since the <code>ergm()</code> function uses a stochastic MCMC-based estimation algorithm, use the <code>set.seed()</code> function and set the value to 2022 (note this could be any number) so we produce the same results each time.</p>
<p>Now let’s estimate our model, save the results as <code>ergm_mod_1</code>, and use the <code>summary()</code> function again to take a look at our estimates. Also,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2022</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>ergm_mod_1 <span class="ot">&lt;-</span><span class="fu">ergm</span>(leader_network <span class="sc">~</span> edges <span class="sc">+</span> mutual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: 'glpk' selected as the solver, but package 'Rglpk' is not available;
falling back to 'lpSolveAPI'. This should be fine unless the sample size and/or
the number of parameters is very big.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ergm_mod_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = leader_network ~ edges + mutual)

Monte Carlo Maximum Likelihood Results:

       Estimate Std. Error MCMC % z value Pr(&gt;|z|)    
edges   -3.1062     0.1170      0  -26.54   &lt;1e-04 ***
mutual   3.1118     0.2766      0   11.25   &lt;1e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 2503.6  on 1806  degrees of freedom
 Residual Deviance:  893.3  on 1804  degrees of freedom
 
AIC: 897.3  BIC: 908.3  (Smaller is better. MC Std. Err. = 0.9914)</code></pre>
</div>
</div>
<p>Since ERGMs predict the presence of a network tie, with estimates indicating the importance of each to the presence of a tie, estimated coefficients can be explained in terms similar to logistic regression. That is, positive significant coefficients indicate that the corresponding parameters in the observed network (e.g.&nbsp;reciprocated ties between school leaders), controlling for all other parameters in the model, occur more than would be expected by chance, thus increasing the likelihood that a tie will occur, and vice-versa for negative coefficients.</p>
<p>After several iterations, we see that our model finally converges and suggest that the estimates for our <code>edges</code> and <code>mutual</code> terms are statistically significant. The negative estimate for the <code>edge</code> paramter, as noted by <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span>, implies that the probability of a confidential exchange tie in year 3 is relatively low. The reciprocity parameter, on the other hand, is 3.11 in our model, and indicates a strong tendency for confidential-exchange ties to be reciprocated.</p>
<p>Now let’s add an ergm-term for transitivity. Modeling transitivity, or the “friend of a friend” phenomenon in social networks, is both computationally intensive because of the all the possible “triangles” in a directed network, and also very prone to model degeneration, i.e.&nbsp;when models that fail to converge by reaching a value expected by the parameters included in the model.</p>
<p>Ergm-terms for transitivity such as <code>triangles</code> and <code>transitive</code> in particular are prone to model degeneration. Fortunately, the {ergm} package includes a “more robust way of modeling triangles: the geometrically-weighed edgewise shared partner term (GWESP).”</p>
<p>Let’s add the <code>gwesp</code> term to our model with the suggested defaults from the Statnet Tutorial section on <a href="http://statnet.org/Workshops/ergm_tutorial.html#What_it_looks_like_when_a_model_fails">What it looks like when a model fails</a> and take a look at the summary first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(leader_network <span class="sc">~</span> edges <span class="sc">+</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>          mutual <span class="sc">+</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>          transitive <span class="sc">+</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>          <span class="fu">gwesp</span>(<span class="fl">0.25</span>, <span class="at">fixed=</span>T))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               edges               mutual           transitive 
            143.0000              36.0000             202.0000 
gwesp.OTP.fixed.0.25 
            116.2971 </code></pre>
</div>
</div>
<p>As you can see, we have 202 transitive triad types.</p>
<p>Now lets run our model including transitivity and take a look at our estimates. Note that this make take a couple minutes to run. If you’d like to watch the number of iterations of the model set <code>message = TRUE</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>ergm_mod_2 <span class="ot">&lt;-</span><span class="fu">ergm</span>(leader_network <span class="sc">~</span> edges <span class="sc">+</span> </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>                    mutual <span class="sc">+</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">gwesp</span>(<span class="fl">0.25</span>, <span class="at">fixed=</span>T))</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ergm_mod_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = leader_network ~ edges + mutual + gwesp(0.25, 
    fixed = T))

Monte Carlo Maximum Likelihood Results:

                     Estimate Std. Error MCMC % z value Pr(&gt;|z|)    
edges                 -3.9736     0.1529      0 -25.980   &lt;1e-04 ***
mutual                 2.3000     0.3280      0   7.011   &lt;1e-04 ***
gwesp.OTP.fixed.0.25   1.0727     0.1311      0   8.185   &lt;1e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 2503.6  on 1806  degrees of freedom
 Residual Deviance:  805.1  on 1803  degrees of freedom
 
AIC: 811.1  BIC: 827.6  (Smaller is better. MC Std. Err. = 0.3991)</code></pre>
</div>
</div>
<p>Contrary to the analysis in Chapter 9, our model so far suggest that there is a tendency toward transitivity, that is a confidential exchange is likely to occur between two people who both have a confidential exchange with the same individual.</p>
<p>At this point, however, we have only focused on structural mechanisms inherent to networks themselves, or “global features” of the graph independent of actors, and have not looked at individual attributes among actors that may be shaping out network.</p>
</section>
<section id="actor-attribute-parameters" class="level4">
<h4 class="anchored" data-anchor-id="actor-attribute-parameters">Actor Attribute Parameters</h4>
<p>As noted by <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span>, ERGMs have advanced to the point where actor attributes, or actor-level covariates, can now be incorporated into model estimation, such as individuals’ demographic (e.g., gender) or behavioral (e.g., efficacy) characteristics. These two attributes examined in Chapter 9 with leadership efficacy measured by survey items based on the <a href="https://wmpeople.wm.edu/asset/index/mxtsch/pse">Principal Efficacy Scale</a>.</p>
<p>The attributes were included as both sender and receiver effects, which again can be very computationally intensive and thus timely to run, while sometimes prone to model degeneracy without some model fine tuning.</p>
<p>To simplify this approach, I’ve include these attributes using the <code>nodefactor()</code> and <code>nocov()</code> ergm-terms respectively which allow us to test whether those who are Male or have higher efficacy scores are more likely to either send or receive a confidential exchange.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>ergm_3 <span class="ot">&lt;-</span> <span class="fu">ergm</span>(leader_network <span class="sc">~</span> edges <span class="sc">+</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>                 mutual <span class="sc">+</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">gwesp</span>(<span class="fl">0.25</span>, <span class="at">fixed=</span>T) <span class="sc">+</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">nodefactor</span>(<span class="st">'male'</span>) <span class="sc">+</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">nodecov</span>(<span class="st">'efficacy'</span>)</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>               )</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ergm_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = leader_network ~ edges + mutual + gwesp(0.25, 
    fixed = T) + nodefactor("male") + nodecov("efficacy"))

Monte Carlo Maximum Likelihood Results:

                     Estimate Std. Error MCMC % z value Pr(&gt;|z|)    
edges                -4.39525    0.39747      0 -11.058   &lt;1e-04 ***
mutual                2.29634    0.30751      0   7.467   &lt;1e-04 ***
gwesp.OTP.fixed.0.25  1.05315    0.13056      0   8.066   &lt;1e-04 ***
nodefactor.male.1     0.10954    0.06262      0   1.749   0.0802 .  
nodecov.efficacy      0.02495    0.02768      0   0.901   0.3674    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 2503.6  on 1806  degrees of freedom
 Residual Deviance:  802.7  on 1801  degrees of freedom
 
AIC: 812.7  BIC: 840.2  (Smaller is better. MC Std. Err. = 0.7829)</code></pre>
</div>
</div>
<p>Although there appears to be a very slight, though not statistically significant tendency towards male leaders being more likely to send or receive ties, the primary drivers of network formation appear to be structural features of the network including reciprocity and transitivity.</p>
<p>Sadly, we were not able to replicate the findings from <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span>, but we also did not replicate their model exactly, nor did we fine tune our model parameters. Regardless, this provided a practical exercise for demonstrating ERGMs.</p>
</section>
<section id="your-turn-8" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-8">👉 Your Turn ⤵</h4>
<p>Before moving on to checking the goodness of fit for our final model, try testing to see if shared characteristics among school leaders might help explain tie formation. To test for homophily among gender or location, the <code>ergm()</code> function includes a <code>nodematch()</code> argument similar to <code>nodefactor()</code> used above that could be used to answer the following question:</p>
<ol type="1">
<li>Controlling for edges, reciprocity, and transitivity, are school leaders more likely to confide in colleagues of their own gender or who work at the same district-site level?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co">#YOUR CODE HERE</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>ergm_4 <span class="ot">&lt;-</span> <span class="fu">ergm</span>(leader_network <span class="sc">~</span> edges <span class="sc">+</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>                 mutual <span class="sc">+</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">gwesp</span>(<span class="fl">0.25</span>, <span class="at">fixed=</span>T) <span class="sc">+</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">nodematch</span>(<span class="st">'male'</span>) <span class="sc">+</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">nodematch</span>(<span class="st">'district_site'</span>)</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>               )</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ergm_4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = leader_network ~ edges + mutual + gwesp(0.25, 
    fixed = T) + nodematch("male") + nodematch("district_site"))

Monte Carlo Maximum Likelihood Results:

                        Estimate Std. Error MCMC % z value Pr(&gt;|z|)    
edges                    -4.2240     0.1814      0 -23.287   &lt;1e-04 ***
mutual                    2.1888     0.2989      0   7.323   &lt;1e-04 ***
gwesp.OTP.fixed.0.25      1.0303     0.1358      0   7.589   &lt;1e-04 ***
nodematch.male           -0.1188     0.1642      0  -0.724    0.469    
nodematch.district_site   0.6124     0.1276      0   4.801   &lt;1e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 2503.6  on 1806  degrees of freedom
 Residual Deviance:  780.7  on 1801  degrees of freedom
 
AIC: 790.7  BIC: 818.2  (Smaller is better. MC Std. Err. = 0.521)</code></pre>
</div>
</div>
<p>Once you’ve checked the summary of your model estimates, write your interpretation of the results below:</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul>
<p>We’ve only scratched the surface for the number of network and node attributes properties that can be tested using ERGMs. Take a look at a <a href="http://statnet.org/nme/d2-ergmterms.html">table of common ergm-terms</a> or type “ergm-terms” into the help menu of the files pane for some additional examples.</p>
</section>
</section>
<section id="c.-check-model-fit" class="level3">
<h3 class="anchored" data-anchor-id="c.-check-model-fit">4c. Check Model Fit</h3>
<p>One test of whether an ergm model is a “good fit” for the data is “how well it reproduces the observed global network properties <em>that are not in the model</em>.” This can be accomplished by choosing a network statistic that is not in the model, and comparing the value of this statistic observed in the original network to the distribution of values we get in simulated networks from our model, using the <code>gof()</code> function to test the goodness-of-fit.</p>
<section id="the-gof-function" class="level4">
<h4 class="anchored" data-anchor-id="the-gof-function">The GOF Function</h4>
<p>The <code>gof()</code> function is a bit different than the <code>summary()</code> and <code>ergm()</code> functions, in that it only takes 3 ergm-terms as arguments: degree, esp (edgwise share partners), and distance (geodesic distances). Each of these terms captures an aggregate network distribution, at either the node level (degree), the edge level (esp), or the dyad level (distance).</p>
<p>Let’s go ahead and run the <code>gof()</code> function on our <code>ergm_3</code> model and plot the results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>ergm_3_gof <span class="ot">&lt;-</span> <span class="fu">gof</span>(ergm_3)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ergm_3_gof)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/ergm-3-gof-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/ergm-3-gof-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/ergm-3-gof-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/ergm-3-gof-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/ergm-3-gof-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Overall, the model appears to fit reasonably well in that black line in our charts (the actual observed network measures) closely follows the aggregate measures generated from the simulations, or permutations of our network.</p>
</section>
<section id="check-mcnc-diagnostics" class="level4">
<h4 class="anchored" data-anchor-id="check-mcnc-diagnostics">Check MCNC Diagnostics</h4>
<p>One final check on our model is to examine the Monte-Carlo Markov Chain (MCMC) diagnostics to make sure our model is not heading of in the wrong direction and likely to never produce a network similar to what was observed, which is referred to as “model degeneracy.” As the statnet authors note:</p>
<blockquote class="blockquote">
<p>When a model is not a good representation of the observed network, the simulated networks produced in the MCMC chains may be far enough away from the observed network that the estimation process is affected. In the worst case scenario, the simulated networks will be so different that the algorithm fails altogether.</p>
</blockquote>
<p>Fortunately, our models did not fail to converge, the AIC and BIC indicators seemed to improve with each term added to the model, and the goodness-of-fit seemed to somewhat mirror the global features of our network.</p>
<p>Let run the <code>mcmc.diagnostics()</code> function on our final model anyways and check the results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mcmc.diagnostics</span>(ergm_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/diagnose-ergm-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/diagnose-ergm-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample statistics summary:

Iterations = 507904:10027008
Thinning interval = 8192 
Number of chains = 1 
Sample size per chain = 1163 

1. Empirical mean and standard deviation for each variable,
   plus standard error of the mean:

                        Mean     SD Naive SE Time-series SE
edges                  8.603  49.15   1.4412          3.488
mutual                 2.878  16.22   0.4755          1.168
gwesp.OTP.fixed.0.25  10.631  61.52   1.8039          4.407
nodefactor.male.1      7.088  55.23   1.6194          4.094
nodecov.efficacy     122.049 668.40  19.5995         47.802

2. Quantiles for each variable:

                         2.5%     25%    50%    75%   97.5%
edges                  -82.00  -27.00  10.00  47.00   95.95
mutual                 -27.00   -9.00   3.00  15.00   33.00
gwesp.OTP.fixed.0.25   -98.51  -36.58  11.03  56.39  128.44
nodefactor.male.1      -95.00  -33.00   9.00  47.00  104.95
nodecov.efficacy     -1104.72 -364.49 149.63 642.15 1336.39


Are sample statistics significantly different from observed?
                edges    mutual gwesp.OTP.fixed.0.25 nodefactor.male.1
diff.      8.60275150 2.8779020          10.63111524         7.0877042
test stat. 2.46632935 2.4650007           2.41231381         1.7311433
P-val.     0.01365058 0.0137013           0.01585163         0.0834262
           nodecov.efficacy       (Omni)
diff.          122.04879622           NA
test stat.       2.55322199 2.941862e+01
P-val.           0.01067314 2.717414e-05

Sample statistics cross-correlations:
                         edges    mutual gwesp.OTP.fixed.0.25 nodefactor.male.1
edges                1.0000000 0.9753759            0.9904000         0.9560965
mutual               0.9753759 1.0000000            0.9785321         0.9353027
gwesp.OTP.fixed.0.25 0.9904000 0.9785321            1.0000000         0.9527651
nodefactor.male.1    0.9560965 0.9353027            0.9527651         1.0000000
nodecov.efficacy     0.9985156 0.9749589            0.9895277         0.9539979
                     nodecov.efficacy
edges                       0.9985156
mutual                      0.9749589
gwesp.OTP.fixed.0.25        0.9895277
nodefactor.male.1           0.9539979
nodecov.efficacy            1.0000000

Sample statistics auto-correlation:
Chain 1 
              edges    mutual gwesp.OTP.fixed.0.25 nodefactor.male.1
Lag 0     1.0000000 1.0000000            1.0000000         1.0000000
Lag 8192  0.7081569 0.7152500            0.7127935         0.6955756
Lag 16384 0.5198161 0.5232778            0.5179172         0.5188637
Lag 24576 0.4012243 0.3929539            0.3937153         0.4046999
Lag 32768 0.2951548 0.2847533            0.2916377         0.2987084
Lag 40960 0.2285933 0.2272518            0.2255917         0.2442938
          nodecov.efficacy
Lag 0            1.0000000
Lag 8192         0.7119513
Lag 16384        0.5213050
Lag 24576        0.3971166
Lag 32768        0.2912666
Lag 40960        0.2270666

Sample statistics burn-in diagnostic (Geweke):
Chain 1 

Fraction in 1st window = 0.1
Fraction in 2nd window = 0.5 

               edges               mutual gwesp.OTP.fixed.0.25 
           0.6372286            0.4513849            0.6778860 
   nodefactor.male.1     nodecov.efficacy 
           0.8926203            0.6729076 

Individual P-values (lower = worse):
               edges               mutual gwesp.OTP.fixed.0.25 
           0.5239760            0.6517121            0.4978440 
   nodefactor.male.1     nodecov.efficacy 
           0.3720605            0.5010061 
Joint P-value (lower = worse):  0.007027049 

Note: MCMC diagnostics shown here are from the last round of
  simulation, prior to computation of final parameter estimates.
  Because the final estimates are refinements of those used for this
  simulation run, these diagnostics may understate model performance.
  To directly assess the performance of the final model on in-model
  statistics, please use the GOF command: gof(ergmFitObject,
  GOF=~model).</code></pre>
</div>
</div>
<p>One simple heuristic for interpreting <code>mcmc.diagnostics()</code> results is too look for “balance.” The charts with all the squiggles, to use a non-technical term, should have a scale that ideally is centered on 0 and have roughly straight line running through it, while the chart that looks like a simple line graph should also be ideally centered at 0 and roughly normally distributed on both ends. Overall, the diagnostics indicate there is room for improvement but nothing is wildly off and hence our model did not fail to converge.</p>
</section>
<section id="your-turn-9" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-9">👉 Your Turn ⤵</h4>
<p>Use the code chunk below to check the model fit and diagnostics for the model the you created in <a href="#b.-estimate-the-ergm">4b. Estimate the ERGM</a>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#YOUR CODE HERE</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>ergm_4_gof <span class="ot">&lt;-</span> <span class="fu">gof</span>(ergm_4)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ergm_4_gof)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/check-ergm-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/check-ergm-4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/check-ergm-4-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/check-ergm-4-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/check-ergm-4-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mcmc.diagnostics</span>(ergm_4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/check-ergm-4-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sna-4-case-study-key-R_files/figure-html/check-ergm-4-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample statistics summary:

Iterations = 434176:8564736
Thinning interval = 4096 
Number of chains = 1 
Sample size per chain = 1986 

1. Empirical mean and standard deviation for each variable,
   plus standard error of the mean:

                          Mean    SD Naive SE Time-series SE
edges                   10.974 39.05   0.8762         2.5069
mutual                   3.601 13.11   0.2942         0.9299
gwesp.OTP.fixed.0.25    13.794 49.28   1.1058         3.1960
nodematch.male           4.608 18.69   0.4195         1.3020
nodematch.district_site  8.701 31.17   0.6995         2.1875

2. Quantiles for each variable:

                          2.5%    25%   50%   75%  97.5%
edges                   -66.00 -17.00 13.00 37.00  85.00
mutual                  -21.38  -6.00  4.00 12.00  28.00
gwesp.OTP.fixed.0.25    -80.48 -21.81 14.66 47.72 108.19
nodematch.male          -31.00  -8.00  5.00 17.00  42.00
nodematch.district_site -54.00 -13.75 11.00 30.00  66.38


Are sample statistics significantly different from observed?
                  edges       mutual gwesp.OTP.fixed.0.25 nodematch.male
diff.      1.097382e+01 3.6007049345         1.379446e+01   4.6077542800
test stat. 4.377458e+00 3.8721604155         4.316120e+00   3.5390536774
P-val.     1.200714e-05 0.0001078749         1.587957e-05   0.0004015642
           nodematch.district_site       (Omni)
diff.                 8.701410e+00           NA
test stat.            3.977760e+00 2.489218e+01
P-val.                6.956759e-05 1.697982e-04

Sample statistics cross-correlations:
                            edges    mutual gwesp.OTP.fixed.0.25 nodematch.male
edges                   1.0000000 0.9601394            0.9861184      0.9451290
mutual                  0.9601394 1.0000000            0.9648794      0.9031541
gwesp.OTP.fixed.0.25    0.9861184 0.9648794            1.0000000      0.9335099
nodematch.male          0.9451290 0.9031541            0.9335099      1.0000000
nodematch.district_site 0.9649489 0.9413189            0.9629812      0.9110336
                        nodematch.district_site
edges                                 0.9649489
mutual                                0.9413189
gwesp.OTP.fixed.0.25                  0.9629812
nodematch.male                        0.9110336
nodematch.district_site               1.0000000

Sample statistics auto-correlation:
Chain 1 
              edges    mutual gwesp.OTP.fixed.0.25 nodematch.male
Lag 0     1.0000000 1.0000000            1.0000000      1.0000000
Lag 4096  0.7623297 0.7720322            0.7650279      0.6846821
Lag 8192  0.6016542 0.6156976            0.6070775      0.5416852
Lag 12288 0.4858923 0.4952195            0.4907923      0.4336396
Lag 16384 0.4028554 0.4227586            0.4078119      0.3622159
Lag 20480 0.3438030 0.3640994            0.3519061      0.3071995
          nodematch.district_site
Lag 0                   1.0000000
Lag 4096                0.7630536
Lag 8192                0.6063097
Lag 12288               0.4927248
Lag 16384               0.4180450
Lag 20480               0.3568916

Sample statistics burn-in diagnostic (Geweke):
Chain 1 

Fraction in 1st window = 0.1
Fraction in 2nd window = 0.5 

                  edges                  mutual    gwesp.OTP.fixed.0.25 
              -1.597076               -1.750655               -1.699352 
         nodematch.male nodematch.district_site 
              -1.593156               -1.517647 

Individual P-values (lower = worse):
                  edges                  mutual    gwesp.OTP.fixed.0.25 
             0.11024875              0.08000541              0.08925282 
         nodematch.male nodematch.district_site 
             0.11112519              0.12910339 
Joint P-value (lower = worse):  0.2981967 

Note: MCMC diagnostics shown here are from the last round of
  simulation, prior to computation of final parameter estimates.
  Because the final estimates are refinements of those used for this
  simulation run, these diagnostics may understate model performance.
  To directly assess the performance of the final model on in-model
  statistics, please use the GOF command: gof(ergmFitObject,
  GOF=~model).</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="communicate" class="level2">
<h2 class="anchored" data-anchor-id="communicate">5. COMMUNICATE</h2>
<p>The final step in the workflow/process is sharing the results of your analysis with wider audience. Krumm et al. <span class="citation" data-cites="krumm2018">Krumm, Means, and Bienkowski (<a href="#ref-krumm2018" role="doc-biblioref">2018</a>)</span> have outlined the following 3-step process for communicating with education stakeholders findings from an analysis:</p>
<ol type="1">
<li><p><strong>Select.</strong> Communicating what one has learned involves selecting among those analyses that are most important and most useful to an intended audience, as well as selecting a form for displaying that information, such as a graph or table in static or interactive form, i.e.&nbsp;a “data product.”</p></li>
<li><p><strong>Polish</strong>. After creating initial versions of data products, research teams often spend time refining or polishing them, by adding or editing titles, labels, and notations and by working with colors and shapes to highlight key points.</p></li>
<li><p><strong>Narrate.</strong> Writing a narrative to accompany the data products involves, at a minimum, pairing a data product with its related research question, describing how best to interpret the data product, and explaining the ways in which the data product helps answer the research question and might be used to inform new analyses or a “change idea” for improving student learning.</p></li>
</ol>
<section id="render-file" class="level3">
<h3 class="anchored" data-anchor-id="render-file">Render File</h3>
<p>For your SNA Badge, you will have an opportunity to create a simple “data product” designed to illustrate some insights gained from your analysis and ideally highlight an action step or change idea that can be used to improve learning or the contexts in which learning occurs.</p>
<p>For now, we will wrap up this case study by converting your work to an HTML file that can be published and used to communicate your learning and demonstrate some of your new R skills. To do so, you will need to “render” your document by clicking the <img src="img/render.png" class="img-fluid" style="width:4.0%"> Render button in the menu bar at that the top of this file.</p>
<p>Rendering a document does two important things:</p>
<ol type="1">
<li><p>checks through all your code for any errors; and,</p></li>
<li><p>creates a file in your directory that you can use to share you work .</p></li>
</ol>
<section id="your-turn-10" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-10">👉 Your Turn ⤵</h4>
<p>Now that you’ve finished your first case study, click the “Render” button in the toolbar at the top of your document to covert this Quarto document to a HTML web page, just one of <a href="https://quarto.org/docs/output-formats/all-formats.html">the many publishing formats you can create with Quarto</a> documents.</p>
<p>If the files rendered correctly, you should now see a new file named <code>sna-4-case-study-R.html</code> in the Files tab located in the bottom right corner of R Studio. If so, congratulations, you just completed the getting started activity! You’re now ready for the unit Case Studies that we will complete during the third week of each unit.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you encounter errors when you try to render, first check the case study answer key located in the files pane and has the suggested code for the Your Turns. If you are still having difficulties, try copying and pasting the error into Google or ChatGPT to see if you can resolve the issue. Finally, contact your instructor to debug the code together if you’re still having issues.</p>
</div>
</div>
</section>
</section>
<section id="publish-file" class="level3">
<h3 class="anchored" data-anchor-id="publish-file">Publish File</h3>
<p>There are a wide variety of ways to publish documents, presentations, and websites created using Quarto. Since content rendered with Quarto uses standard formats (HTML, PDFs, MS Word, etc.) it can be published anywhere. Additionally, there is a <code>quarto publish</code> command available for easy publishing to various popular services such as <a href="#0">Quarto Pub</a>, <a href="#0">Posit Cloud</a>, <a href="#0">RPubs</a> , <a href="#0">GitHub Pages</a>, or <a href="#0">other services</a>.</p>
<section id="your-turn-11" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-11">👉 Your Turn ⤵</h4>
<p>Choose of of the following methods described below for publishing your completed case study.</p>
</section>
<section id="publishing-with-quarto-pub" class="level4">
<h4 class="anchored" data-anchor-id="publishing-with-quarto-pub">Publishing with Quarto Pub</h4>
<p>Quarto Pub is a free publishing service for content created with Quarto. Quarto Pub is ideal for blogs, course or project websites, books, reports, presentations, and personal hobby sites.</p>
<p>It’s important to note that all documents and sites published to Quarto Pub are <strong>publicly visible</strong>. You should only publish content you wish to share publicly.</p>
<p>To publish to Quarto Pub, you will use the&nbsp;<code>quarto publish</code>&nbsp;command to publish content rendered on your local machine or via Posit Cloud.</p>
<p>Before attempting your first publish, be sure that you have created a free&nbsp;<a href="https://quartopub.com/">Quarto Pub</a>&nbsp;account.</p>
<p>The <code>quarto publish</code>&nbsp;command provides a very straightforward way to publish documents to Quarto Pub.</p>
<p>For example, here is the Terminal command to publish a generic Quarto <code>document.qmd</code> to each of this service:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>Terminal</strong></pre>
</div>
<div class="sourceCode" id="cb78" data-filename="Terminal"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> publish quarto-pub document.qmd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can access your the terminal from directly <strong>Terminal Pane</strong> in the lower left corner as shown below:</p>
<p><img src="img/terminal.png" class="img-fluid" style="width:100.0%"></p>
<p>The actual command you will enter into your terminal to publish your orientation case study is:</p>
<p><code>quarto publish quarto-pub sna-4-case-study-R.qmd</code></p>
<p>When you publish to Quarto Pub using <code>quarto publish</code> an access token is used to grant permission for publishing to your account. The first time you publish to Quarto Pub the Quarto CLI will automatically launch a browser to authorize one as shown below.</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>Terminal</strong></pre>
</div>
<div class="sourceCode" id="cb79" data-filename="Terminal"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> quarto publish quarto-pub</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="ex">?</span> Authorize <span class="er">(</span><span class="ex">Y/n</span><span class="kw">)</span> <span class="ex">›</span> </span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="ex">❯</span> In order to publish to Quarto Pub you need to</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  <span class="ex">authorize</span> your account. Please be sure you are</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="ex">logged</span> into the correct Quarto Pub account in </span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>  <span class="ex">your</span> default web browser, then press Enter or </span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">'Y'</span> to authorize.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Authorization will launch your default web browser to confirm that you want to allow publishing from Quarto CLI. An access token will be generated and saved locally by the Quarto CLI.</p>
<p>Once you’ve authorized Quarto Pub and published your case study, it should take you immediately to the published document. See my example Orientation Case Study complete with answer key here: <a href="https://sbkellogg.quarto.pub/laser-orientation-case-study-key/">https://sbkellogg.quarto.pub/laser-orientation-case-study-key</a>.</p>
<p>After you’ve published your first document, you can continue adding more documents, slides, books and even publish entire websites!</p>
<p><img src="img/quarto-pub.png" class="img-fluid"></p>
</section>
<section id="publishing-with-r-pubs" class="level4">
<h4 class="anchored" data-anchor-id="publishing-with-r-pubs">Publishing with R Pubs</h4>
<p>An alternative, and perhaps the easiest way to quickly publish your file online is to publish directly from RStudio using Posit Cloud or RPubs. You can do so by clicking the “Publish” button located in the Viewer Pane after you render your document and as illustrated in the screenshot below.</p>
<p><img src="img/publish.png" class="img-fluid" style="width:100.0%"></p>
<p>Similar to Quarto Pub, be sure that you have created a free Posit Cloud or R Pub account before attempting your first publish. You may also need to add your Posit Cloud or R Pub account before being able to publish.</p>
<p>Congratulations, you’ve completed the case study! You’re now ready to dig into the essential readings and try out your next SNA LASER Badge!</p>
</section>
</section>
<section id="references" class="level3 unnumbered">


</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-carolan2014" class="csl-entry" role="listitem">
Carolan, Brian. 2014. <span>“Social Network Analysis and Education: Theory, Methods &amp; Applications.”</span> <a href="https://doi.org/10.4135/9781452270104">https://doi.org/10.4135/9781452270104</a>.
</div>
<div id="ref-krumm2018" class="csl-entry" role="listitem">
Krumm, Andrew, Barbara Means, and Marie Bienkowski. 2018. <em>Learning Analytics Goes to School</em>. Routledge. <a href="https://doi.org/10.4324/9781315650722">https://doi.org/10.4324/9781315650722</a>.
</div>
<div id="ref-mcpherson1987homophily" class="csl-entry" role="listitem">
McPherson, J Miller, and Lynn Smith-Lovin. 1987. <span>“Homophily in Voluntary Organizations: Status Distance and the Composition of Face-to-Face Groups.”</span> <em>American Sociological Review</em>, 370–79.
</div>
<div id="ref-handcock" class="csl-entry" role="listitem">
Pavel N. Krivitsky, Mark S. Handcock, David R. Hunter, Carter T. Butts, Chad Klumb, Steven M. Goodreau, and Martina Morris. 2003-2020. <em>Statnet: Software Tools for the Statistical Modeling of Network Data</em>. Statnet Development Team. <a href="http://statnet.org">http://statnet.org</a>.
</div>
<div id="ref-thomas2011valued" class="csl-entry" role="listitem">
Thomas, Andrew C, and Joseph K Blitzstein. 2011. <span>“Valued Ties Tell Fewer Lies: Why Not to Dichotomize Network Edges with Thresholds.”</span> <em>arXiv Preprint arXiv:1101.0788</em>. <a href="https://arxiv.org/pdf/1101.0788.pdf">https://arxiv.org/pdf/1101.0788.pdf</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>