---
title: "Essential Readings: Statistical Inference & Network Modeling"
subtitle: "LASER Institute SNA Learning Lab 3"
author: "Dr. Shaun Kellogg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
editor_options:
  markdown:
    wrap: 72
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

In Lab 3 we examine the use of different algorithms to analyze a
network's groups, positions and individual actors. The required and
self-selected readings introduce both "top-down" and "bottom-up"
approaches through which groups are identified, as well as ways in which
properties of ego networks are conceptualized and measured. A secondary
goal of readings and discussion is to help you start generating ideas
for independent application of network analysis. As part of our
readings, for example, you'll learn approaches to identifying groups
appropriate to your own research area of interest.

## Readings

For Lab 3, you will read chapters 6 and7 from [Social Network Analysis
and Education](https://catalog.lib.ncsu.edu/catalog/NCSU2803782)
[@carolan2014] and locate one additional research article, presentation,
or informal study to help address our discussion questions for the week.

### SNA and Education Part II: Methods and Measures

The second half of Part II focuses on ways to partition a network into
groups based on relations rather than on the attributes that one may
share with others. In addition, we learn how a network can also be
divided into distinct positions, i.e. actors who occupy similar
positions have similar relations to others but need not be directly tied
to each other.

1.  [Chapter 6: Groups and Positions in Complete
    Networks](https://github.com/laser-institute/essential-readings/blob/main/sna-labs/sna-lab-3/carolan-group-analysis.pdf)

2.  [Chapter 7: Measures for Egocentric Network
    Analysis](https://github.com/laser-institute/essential-readings/blob/main/sna-labs/sna-lab-3/carolan-egocentric-analysis.pdf)

### Self-Selected Study

Use your institutional library (e.g., [NCSU
Library](https://www.lib.ncsu.edu/#articles)), [Google
Scholar](https://scholar.google.com/) or search engine to locate a
research or practitioner-focused article, presentation, or resource that
applies social network analysis to an educational context or topic of
interest. More specifically, **locate an network study that makes use of
group or egocentric analysis to understand and educational context.**
You are also welcome to select one of the research papers cited in our
essential readings that may have peaked your interest. Your selection
should address one or more of the discussion topics/questions (see
below) and you're welcome to identify SNA resources outside of the field
of education.

## Reflection

To help guide your reflection on the readings, a set of guiding
questions are provided below. After you have had a chance to work
through one or more of the readings, **we encourage you to contribute to
our learning community by creating a new post to our [Social Network
Analysis
Team](https://github.com/orgs/laser-institute/teams/network-analysis) on
GitHub**. You post might contain a response to one or more of the
guiding questions, questions you still have about the topics addressed,
or insights gained into your own research.

### Self-Selected Study

For your self-selected study, think about the following questions
depending on whether your article focused on group, positional, or
egocentric analysis:

#### **Group or Positional Analysis**

1.  How has a group been defined and measured? Were any alternatives
    considered? Does this definition of a group make sense given the
    network's actors and relations among them? Is this definition
    restrictive or flexible?

2.  Was a "top-down" or "bottom-up" approach used? Both?

3.  How were the network's positions defined and measured? How do these
    positions differ from the network's groups? Is this difference made
    evident? What definition of equivalence informed the definition and
    measurement of the network's positions? Was a reduced-form network
    presented? What does it indicate about the network's hierarchy?

#### **Egocentric Analysis**

1.  What makes this an egocentric network study? How were the egocentric
    network data collected? What measures of egos' networks were
    included in the analysis?

2.  Assume you wanted to examine whether a student's popularity was
    associated with her or his attachment to school. How could you use a
    measure introduced in this chapter to capture "popularity"? Why did
    you select this measure over any others? Would you simply need
    ego-to-alter data or also alter-to-alter data?

3.  If you wanted to examine the process through which a school reform
    initiative spreads throughout a school district, which egocentric
    concepts and measures would you employ?Chapter 5: Structural
    Measures for Complete Networks

### Chapter 6: Groups and Positions in Complete Networks

Consider a network of which you are a part or a network you might be
interested in studying and answer the following questions:

1.  What types of groups and/or unique positions do you think might be
    identified through relational data (e.g., friendships, advice
    seeking, co-authorship, communication, collaboration, etc.)?

2.  How might membership in those groups, or occupying certain
    positions, "influence" attitudes, behaviors, or outcomes for those
    individuals?

3.  How might characteristics or attributes differ between groups or
    positions?

4.  What research question(s) could you explore for this network?

As Carolan notes in Chapter 6, sometimes researchers use a cut-off value
from valued data to identify whether a relationship between two nodes
exists or not before analyzing the data. For example,

1.  How did Daly and Finnagan @daly2011ebb use cut-off values in their
    study and what was the rationale?

2.  What might be some advantages and disadvantages of using cut-off
    values in networks with valued ties?

### Chapter 7: Measures for Egocentric Network Analysis

Draft a research question for an egocentric analysis of a population you
may be interested in studying, or that would be of interest to
educational researchers.

Share your research question and then answer the following questions:

1.  What methods might you employ to capture egocentric data to address
    this question?

2.  What questions would you ask in order to identify ego's alters?

3.  What other information about the alters might you collected?

4.  What egocentric measures would you use to address your
    question(s)?If a measure of centrality, which might you choose and
    why?

## References
