---
title: "Unit 4 Readings: Statistical Inference & Network Modeling"
subtitle: "ECI 589 Social Network Analysis and Education"
author: "Dr. Shaun Kellogg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
editor_options:
  markdown:
    wrap: 72
bibliography: lit/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

In Unit 4 we shift our focus from mathematical approaches for describing
networks to statistical approaches for explaining and ultimately
predicting network properties and outcomes for those embedded within
these networks. A secondary goal of readings and discussion is to help
you start generating ideas for independent application of network
analysis. As part of our readings, for example, you'll be introduced to
a range of questions that statistical models for network data can help
answer.

## Readings

For Unit 3, you will read chapters 8 and 9 from [Social Network Analysis
and Education](https://catalog.lib.ncsu.edu/catalog/NCSU2803782)
[@carolan2014] and locate one additional research article, presentation,
or informal study to help address our discussion questions for the week.

### SNA and Education Part III: Applications and Examples

The following readings move us beyond techniques introduced in Parts I &
II for describing networks and focuses on recent advances in inferential
statistics that can be used to make predictions from social network data
and test hypotheses we have about a network of interest. We'll learn
about different techniques that make use of simulations to model network
data and how these statistical models are used to address questions that
more completely reflect the complexity of educational settings.

1.  [Chapter 8: An Introduction to Statistical Inference With Network
    Data](https://methods-sagepub-com.prox.lib.ncsu.edu/book/social-network-analysis-and-education/n8.xml)

2.  [Chapter 9: Network Data and Statistical
    Models](https://methods-sagepub-com.prox.lib.ncsu.edu/book/social-network-analysis-and-education/n9.xml)

### Self-Selected Study

Use the [NCSU Library](https://www.lib.ncsu.edu/#articles), [Google
Scholar](https://scholar.google.com/) or search engine to locate a
research or practitioner-focused article, presentation, or resource that
applies social network analysis to an educational context or topic of
interest. More specifically, **locate an network study that makes use of
statistical models to explain or predict an education related process or
outcome.** You are also welcome to select one of the research papers
listed in the [syllabus](https://sbkellogg.github.io/eci-589/) or in our
[course text](https://catalog.lib.ncsu.edu/catalog/NCSU2803782) that may
have peaked your interest. Your selection should address one or more of
the discussion topics/questions (see below) and you're welcome to
identify SNA resources outside of the field of education.

## Discussion

In lieu of the peer interaction and discussion of course materials that
normally take place "in-class", you'll be asked to log in this week
and engage with other members of our learning community through this
discussion forum. **With the exception of the Self-Selected Study
questions, you are not required to address every guiding question**,
particularly if you feel others in the class have thoroughly addressed
the topic or questions. Our aim for these discussions is to collectively
build our understanding of these readings through back-and-forth
dialogue and avoid a "collective monologue" in which we see 20
variations of effectively the same post.

To create a new post in response to one or more of the guiding questions
listed below, click "Add a new discussion topic" located below the forum
overview text and add a descriptive title for the subject line. In the
message box, includes the question(s) your post is addressing, as well
as your response to the selected questions. Remember, you are not
required to address every guiding question with the exception of the
Self-Selected Study questions for which you must create one new
discussion topic and respond to the discussion prompt and required
questions.

### Guiding Questions

To help guide our discussions, we will collectively address a set of
guiding questions provided below. You are also welcome to add your own
topics or questions for the class to discuss.

#### Self-Selected Study

For your self-selected study, provide an APA citation and abstract, then
briefly answer the following questions as appropriate:

-   What is being modeled: ties in complete networks, individual actor
    attributes, or groups of actors?

-   What procedure was used and what, if any, covariates were included
    in the models? At what level were these covariates measured:
    continuous (ratio or interval) or categorical?

-   Did the modeling strategy measure a network's change over time?

-   How, if at all, were simulations used to create a probability
    distribution against which observed network parameters were
    compared?

-   What does it mean when the result from a statistical model using
    network data is reported as being "statistically significant"? How
    does this relate to the implied null hypothesis?

#### Chapter 8: Statistical Inference With Network Data

Answer one or more of the following questions:

-   Why are simulations necessary in order to make probabilistic
    inferences with network data?
-   Explain in plain language how simulations are used to create a
    probability distribution that enables you to make a statistical
    inference with network data.
-   Contrast the aims of the mathematical and statistical approaches to
    social network analysis. For what reasons would educational
    researchers prefer one approach versus the other?

#### Chapter 9: Network Data and Statistical Models

Using one of the studies mentioned throughout this chapter, identify the
statistical model that was employed and answer one or more the following
questions:

-   Do you think the choice of statistical model(s) used was
    appropriate?

-   If this same study were to use standard statistical models that
    assume independence among observations, how would this influence the
    study's results?

-   Assume you had network data from an entire high school student body
    (N = 250) and were interested in predicting a student's number of
    friends from covariates such as sex, grade level, and academic
    performance. What model would be most appropriate to test these
    relationships?

## Assessment

Grading for this assignment is fairly lenient, provided that it's clear
from your posts that you've done the required reading. Readings and
discussion for each unit are worth 6 points and judged based on quantity
and quality of your posts.

In term of **quantity** (3 points), you'll be expected to create at
least 4 posts. One post should answer each of the questions for your
self-selected study and three posts and/or replies that help us
collectively address the questions for the required readings. So others
will have an opportunity to read and respond to your posts, your posts
should be spread out over the course of the week and across at least two
different days, preferably not the last two days.

In terms of **quality** (3 points), your posts over the next week should
provide new or insightful contributions to that question or topic.
There is no requisite for the length of each posting, in fact short
conversational exchanges (1-3 paragraphs) are highly encouraged. I
strongly recommend taking a look at Table 1 of [the productive online
discussion
model](https://moodle-courses2122.wolfware.ncsu.edu/pluginfile.php/287931/mod_forum/post/6203/Gao%2C%20Wang%2C%20Sun%20-%202009%20-%20A%20new%20model%20of%20productive%20online%20discussion%20and%20its%20implications%20for%20research%20and%20instruction.pdf) [@gao2009]
for ways to contribute to the conversation. 

At minimum, your collective posts should also help us interpret or
elaborate on discussion topics, questions, or ideas others have shared
by "making connection to the learning materials" and should reference at
some point each of the required chapters and your self-selected reading
or resource.

## References
