---
title: 'Unit 3 Readings: Groups, Positions, & Egocentric Analysis '
subtitle: "ECI 589 Social Network Analysis and Education"
author: "Dr. Shaun Kellogg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
editor_options:
  markdown:
    wrap: 72
bibliography: lit/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

Our primary goal in this unit is to examine the use of different
algorithms to analyze a network's groups, positions and individual
actors. The required and self-selected readings introduce both
"top-down" and "bottom-up" approaches through which groups are
identified, as well as ways in which properties of ego networks are
conceptualized and measured. A secondary goal of readings and discussion
is to help you start generating ideas for independent application of
network analysis. As part of our readings, for example, you'll learn
approaches to identifying groups appropriate to your own research area
of interest.

## Readings

For Unit 3, you will read chapters 6 and7 from [Social Network Analysis
and Education](https://catalog.lib.ncsu.edu/catalog/NCSU2803782)
[@carolan2014] and locate one additional research article, presentation,
or informal study to help address our discussion questions for the week.

### SNA and Education Part II: Methods and Measures

The second half of Part II focuses on ways to partition a network into
groups based on relations rather than on the attributes that one may
share with others. In addition, we learn how a network can also be
divided into distinct positions, i.e. actors who occupy similar
positions have similar relations to others but need not be directly tied
to each other.

1.  [Chapter 6: Groups and Positions in Complete
    Networks](https://methods-sagepub-com.prox.lib.ncsu.edu/book/social-network-analysis-and-education/n6.xml)

2.  [Chapter 7: Measures for Egocentric Network
    Analysis](https://methods-sagepub-com.prox.lib.ncsu.edu/book/social-network-analysis-and-education/n7.xml)

### Self-Selected Study

Use the [NCSU Library](https://www.lib.ncsu.edu/#articles), [Google
Scholar](https://scholar.google.com/) or search engine to locate a
research or practitioner-focused article, presentation, or resource that
applies social network analysis to an educational context or topic of
interest. More specifically, **locate an egocentric network study OR a
study that identifies a network's groups and/or positions.** You are
also welcome to select one of the research papers listed in the
[syllabus](https://sbkellogg.github.io/eci-589/) or in our [course
text](https://catalog.lib.ncsu.edu/catalog/NCSU2803782) that may have
peaked your interest. Your selection should address one or more of the
discussion topics/questions (see below) and you're welcome to identify
SNA resources outside of the field of education.

## Discussion

In lieu of the peer interaction and discussion of course materials that
normally take place "in-class", you'll be asked to log in this
week and engage with other members of our learning community through
this discussion forum. **With the exception of the Self-Selected Study
questions, you are not required to address every guiding question**,
particularly if you feel others in the class have thoroughly addressed
the topic or questions. Our aim for these discussions is to collectively
build our understanding of these readings through back-and-forth
dialogue and avoid a "collective monologue" in which we see 20
variations of effectively the same post.

To create a new post in response to one or more of the guiding questions
listed below, click "Add a new discussion topic" located below the forum
overview text and add a descriptive title for the subject line. In the
message box, includes the question(s) your post is addressing, as well
as your response to the selected questions. Remember, you are not
required to address every guiding question with the exception of the
Self-Selected Study questions for which you must create one new
discussion topic and respond to the discussion prompt and required
questions.

### Guiding Questions

To help guide our discussions, we will collectively address a set of
guiding questions provided below. You are also welcome to add your own
topics or questions for the class to discuss.

#### Self-Selected Study (Required)

For your self-selected study, provide an APA citation and abstract, then
briefly answer the following questions depending on whether your article
focused on group, positional, or egocentric analysis:

**Group or Positional Analysis**

1.  How has a group been defined and measured? Were any alternatives
    considered? Does this definition of a group make sense given the
    network's actors and relations among them? Is this definition
    restrictive or flexible?

2.  Was a "top-down" or "bottom-up" approach used? Both?

3.  How were the network's positions defined and measured? How do these
    positions differ from the network's groups? Is this difference made
    evident? What definition of equivalence informed the definition and
    measurement of the network's positions? Was a reduced-form network
    presented? What does it indicate about the network's
    hierarchy?Chapter 4: Basic Concepts (Required)

**Egocentric Analysis**

1.  What makes this an egocentric network study? How were the egocentric
    network data collected? What measures of egos' networks were
    included in the analysis?

2.  Assume you wanted to examine whether a student's popularity was
    associated with her or his attachment to school. How could you use a
    measure introduced in this chapter to capture "popularity"? Why did
    you select this measure over any others? Would you simply need
    ego-to-alter data or also alter-to-alter data?

3.  If you wanted to examine the process through which a school reform
    initiative spreads throughout a school district, which egocentric
    concepts and measures would you employ?Chapter 5: Structural
    Measures for Complete Networks

#### Chapter 6: Groups and Positions in Complete Networks

Consider a network of which you are a part or a network you might be
interested in studying and answer the following questions:

1.  What types of groups and/or unique positions do you think might be
    identified through relational data (e.g., friendships, advice
    seeking, co-authorship, communication, collaboration, etc.)?

2.  How might membership in those groups, or occupying certain
    positions, "influence" attitudes, behaviors, or outcomes for those
    individuals?

3.  How might characteristics or attributes differ between groups or
    positions?

4.  What research question(s) could you explore for this network?

As Carolan notes in Chapter 6, sometimes researchers use a cut-off value
from valued data to identify whether a relationship between two nodes
exists or not before analyzing the data. For example,

1.  How did Daly and Finnagan @daly2011ebb use cut-off values in their
    study and what was the rationale?

2.  What might be some advantages and disadvantages of using cut-off
    values in networks with valued ties?

#### Chapter 7: Measures for Egocentric Network Analysis

Draft a research question for an egocentric analysis of a population you
may be interested in studying, or that would be of interest to
educational researchers.

Share your research question and then answer the following questions:

1.  What methods might you employ to capture egocentric data to address
    this question?

2.  What questions would you ask in order to identify ego's alters?

3.  What other information about the alters might you collected?

4.  What egocentric measures would you use to address your
    question(s)?If a measure of centrality, which might you choose and
    why?

## Assessment

Grading for this assignment is fairly lenient, provided that it's clear
from your posts that you've done the required reading. Readings and
discussion for each unit are worth 6 points and judged based on quantity
and quality of your posts.

In term of **quantity** (3 points), you'll be expected to create at
least 4 posts. One post should answer each of the questions for your
self-selected study and three posts and/or replies that help us
collectively address the questions for the required readings. So others
will have an opportunity to read and respond to your posts, your posts
should be spread out over the course of the week and across at least two
different days, preferably not the last two days.

In terms of **quality** (3 points), your posts over the next week should
provide new or insightful contributions to that question or topic.
There is no requisite for the length of each posting, in fact short
conversational exchanges (1-3 paragraphs) are highly encouraged. I
strongly recommend taking a look at Table 1 of [the productive online
discussion
model](https://moodle-courses2122.wolfware.ncsu.edu/pluginfile.php/287931/mod_forum/post/6203/Gao%2C%20Wang%2C%20Sun%20-%202009%20-%20A%20new%20model%20of%20productive%20online%20discussion%20and%20its%20implications%20for%20research%20and%20instruction.pdf) [@gao2009]
for ways to contribute to the conversation. 

At minimum, your collective posts should also help us interpret or
elaborate on discussion topics, questions, or ideas others have shared
by "making connection to the learning materials" and should reference at
some point each of the required chapters and your self-selected reading
or resource.

## References
